export const CATEGORIES = [
  { value: 'plumbing',      label: '🔧 אינסטלציה' },
  { value: 'electricity',   label: '⚡ חשמלאות' },
  { value: 'handyman',      label: '🔨 הנדימן / תיקונים' },
  { value: 'cleaning',      label: '🧹 ניקיון' },
  { value: 'moving',        label: '🚛 הובלה' },
  { value: 'heavy_lifting', label: '💪 עזרה פיזית' },
  { value: 'painting',      label: '🎨 צביעה' },
  { value: 'carpentry',     label: '🪵 נגרות' },
  { value: 'ac',            label: '❄️ מזגנים' },
  { value: 'locksmith',     label: '🔐 מנעולן' },
  { value: 'gardening',     label: '🌿 גינון' },
  { value: 'home_maintenance', label: '🏠 תחזוקת בית' },
  { value: 'transportation', label: '🚗 הסעות וטרמפים' },
  { value: 'delivery',      label: '📦 משלוח' },
  { value: 'shopping',      label: '🛒 קניות' },
  { value: 'pets',          label: '🐶 בעלי חיים' },
  { value: 'babysitting',   label: '👶 בייביסיטר' },
  { value: 'elderly_care',  label: '👵 סיוע לקשישים' },
  { value: 'tutoring',      label: '📚 שיעורים פרטיים' },
  { value: 'fitness',       label: '🏋️ כושר וספורט' },
  { value: 'photography',   label: '📸 צילום ותוכן' },
  { value: 'events',        label: '🎉 אירועים' },
  { value: 'personal_help', label: '🤝 עזרה אישית' },
  { value: 'it_support',    label: '💻 מחשבים' },
  { value: 'other',         label: '📋 אחר' },
];

export const getCategoryLabel = (value) =>
  CATEGORIES.find(c => c.value === value)?.label || '📋 אחר';