// Category-specific workflow and rating configuration
// Single source of truth for per-category customization of ActiveTaskBanner and RatingModal
// Groups 25 categories into 6 workflow types, each with tailored steps, labels, and rating questions

export const WORKFLOW_TYPES = {
  // ── Onsite service: plumbing, electricity, handyman, cleaning, etc. ──
  onsite_service: {
    statusMap: {
      on_the_way: { label: 'בדרך', ownerLabel: 'בדרך אליך', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'הגיע', ownerLabel: 'הגיע', step: 1 },
      starting: { label: 'מתחיל עבודה', ownerLabel: 'בעבודה', step: 1 },
      finishing: { label: 'מסיים עבודה', ownerLabel: 'מסיים', step: 1 },
      done: { label: 'ממתין לאישור', ownerLabel: 'ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'בדרך', icon: 'navigation' },
      { label: 'הגיע', icon: 'map_pin' },
      { label: 'סיים', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לדרך', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לדרך', confirmSub: 'המפרסם יקבל עדכון שאתה בדרך למיקום' },
      arrive: { label: 'הגעתי למיקום', emoji: '📍', icon: 'map_pin', confirmTitle: 'אישור הגעה', confirmSub: 'המפרסם יקבל עדכון שהגעת למיקום ומתחיל בעבודה' },
      done: { label: 'סיימתי את העבודה', emoji: '✅', icon: 'check', confirmTitle: 'אישור סיום עבודה', confirmSub: 'המפרסם יקבל עדכון שהעבודה הסתיימה ויוכל לאשר תשלום' },
    },
    proofLabel: 'הוכחת ביצוע',
    proofSub: 'תמונות/סרטון לפני ואחרי — מוצגות למפרסם המשימה',
    rating: {
      ownerHeader: (name) => `איך הייתה העבודה עם ${name}?`,
      workerHeader: 'דרג את בעל המשימה',
      ownerSub: 'הביקורת שלך עוזרת לעובדים אחרים לדעת למה לצפות',
      workerSub: 'הביקורת תעזור לבעל המשימה לשפר את החוויה לעובדים הבאים',
      ownerChipsLabel: 'מה היה טוב? (לא חובה)',
      workerChipsLabel: 'איך היה הלקוח?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע בזמן' },
        { key: 'professional', label: '💼 מקצועיות' },
        { key: 'goodCommunication', label: '💬 תקשורת טובה' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אשכור שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ תיאם מראש' },
        { key: 'goodCommunication', label: '💬 הסבר ברור' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אעבוד שוב' },
      ],
      ownerConfirmTitle: '✅ העבודה בוצעה לשביעות רצוני',
      ownerConfirmSub: 'אשר שהתשלום יבוצע כמוסכם והעבודה הושלמה כראוי',
      workerConfirmTitle: '✅ ביצעתי את העבודה בהצלחה',
      workerConfirmSub: 'אשר שסיימת את העבודה והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שהעבודה הושלמה כראוי',
      workerErrorToast: 'יש לאשר שסיימת את העבודה',
    },
  },

  // ── Delivery: delivery, transportation, shopping ──
  delivery: {
    statusMap: {
      on_the_way: { label: 'יצא לאיסוף', ownerLabel: 'יצא לאיסוף', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'נאסף — בדרך למסירה', ownerLabel: 'נאסף — בדרך למסירה', step: 1 },
      starting: { label: 'בדרך למסירה', ownerLabel: 'בדרך למסירה', step: 1 },
      finishing: { label: 'כמעט הגיע למסירה', ownerLabel: 'כמעט הגיע', step: 1 },
      done: { label: 'נמסר — ממתין לאישור', ownerLabel: 'נמסר — ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'איסוף', icon: 'navigation' },
      { label: 'בדרך', icon: 'truck' },
      { label: 'נמסר', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לאיסוף', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לאיסוף', confirmSub: 'המפרסם יקבל עדכון שיצאת לאסוף את המשלוח' },
      arrive: { label: 'נאסף — בדרך למסירה', emoji: '📦', icon: 'truck', confirmTitle: 'אישור איסוף', confirmSub: 'המפרסם יקבל עדכון שהמשלוח נאסף ובדרך למסירה' },
      done: { label: 'המשלוח נמסר', emoji: '✅', icon: 'check', confirmTitle: 'אישור מסירה', confirmSub: 'המפרסם יקבל עדכון שהמשלוח נמסר בהצלחה ויוכל לאשר תשלום' },
    },
    proofLabel: 'אישור מסירה',
    proofSub: 'צלם את המשלוח במקום המסירה — מוצג למפרסם המשימה',
    rating: {
      ownerHeader: (name) => `איך היה המשלוח עם ${name}?`,
      workerHeader: 'דרג את השולח',
      ownerSub: 'הביקורת שלך עוזרת לשולחים אחרים לדעת למה לצפות',
      workerSub: 'הביקורת תעזור לשולח לשפר את החוויה למובילים הבאים',
      ownerChipsLabel: 'מה היה טוב במשלוח? (לא חובה)',
      workerChipsLabel: 'איך היה השולח?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ נמסר בזמן' },
        { key: 'professional', label: '📦 טיפל ביסודיות' },
        { key: 'goodCommunication', label: '💬 עדכן לאורך הדרך' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אשתמש שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ היה מוכן בזמן' },
        { key: 'goodCommunication', label: '💬 כתובת והנחיות ברורות' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אעביר שוב' },
      ],
      ownerConfirmTitle: '✅ המשלוח התקבל במלואו',
      ownerConfirmSub: 'אשר שהמשלוח הגיע שלם והתשלום יבוצע כמוסכם',
      workerConfirmTitle: '✅ המשלוח נמסר בהצלחה',
      workerConfirmSub: 'אשר שמסרת את המשלוח והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שהמשלוח התקבל',
      workerErrorToast: 'יש לאשר שהמשלוח נמסר',
    },
  },

  // ── Care: babysitting, elderly_care, pets ──
  care: {
    statusMap: {
      on_the_way: { label: 'בדרך', ownerLabel: 'בדרך אליך', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'התחיל טיפול', ownerLabel: 'הטיפול התחיל', step: 1 },
      starting: { label: 'בטיפול', ownerLabel: 'בטיפול', step: 1 },
      finishing: { label: 'מסיים טיפול', ownerLabel: 'מסיים', step: 1 },
      done: { label: 'סיים — ממתין לאישור', ownerLabel: 'סיים — ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'בדרך', icon: 'navigation' },
      { label: 'בטיפול', icon: 'heart' },
      { label: 'סיים', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לדרך', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לדרך', confirmSub: 'המפרסם יקבל עדכון שאתה בדרך' },
      arrive: { label: 'התחלתי טיפול', emoji: '🤗', icon: 'heart', confirmTitle: 'תחילת טיפול', confirmSub: 'המפרסם יקבל עדכון שהגעת והטיפול התחיל' },
      done: { label: 'סיימתי טיפול', emoji: '✅', icon: 'check', confirmTitle: 'אישור סיום טיפול', confirmSub: 'המפרסם יקבל עדכון שהטיפול הסתיים ויוכל לאשר תשלום' },
    },
    proofLabel: 'עדכון סיום',
    proofSub: 'תעד את סיום הטיפול — מוצג למפרסם המשימה',
    rating: {
      ownerHeader: (name) => `איך היה הטיפול עם ${name}?`,
      workerHeader: 'דרג את המפרסם',
      ownerSub: 'הביקורת שלך עוזרת למשפחות אחרות לדעת למה לצפות',
      workerSub: 'הביקורת תעזור למפרסם לשפר את החוויה למטפלים הבאים',
      ownerChipsLabel: 'מה היה טוב בטיפול? (לא חובה)',
      workerChipsLabel: 'איך היה המפרסם?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע בזמן' },
        { key: 'professional', label: '🤗 סבלני ואכפתי' },
        { key: 'goodCommunication', label: '💬 תקשורת טובה' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אשמח להפקיד שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ חזר בזמן' },
        { key: 'goodCommunication', label: '💬 הנחיות ברורות' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אשמח לטפל שוב' },
      ],
      ownerConfirmTitle: '✅ הטיפול בוצע לשביעות רצוני',
      ownerConfirmSub: 'אשר שהטיפול עבר בהצלחה והתשלום יבוצע כמוסכם',
      workerConfirmTitle: '✅ סיימתי את הטיפול בהצלחה',
      workerConfirmSub: 'אשר שסיימת את הטיפול והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שהטיפול עבר בהצלחה',
      workerErrorToast: 'יש לאשר שסיימת את הטיפול',
    },
  },

  // ── Session: tutoring, fitness ──
  session: {
    statusMap: {
      on_the_way: { label: 'בדרך', ownerLabel: 'בדרך אליך', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'התחיל שיעור', ownerLabel: 'השיעור התחיל', step: 1 },
      starting: { label: 'בשיעור', ownerLabel: 'בשיעור', step: 1 },
      finishing: { label: 'מסיים שיעור', ownerLabel: 'מסיים', step: 1 },
      done: { label: 'סיים — ממתין לאישור', ownerLabel: 'סיים — ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'בדרך', icon: 'navigation' },
      { label: 'בשיעור', icon: 'book' },
      { label: 'סיים', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לדרך', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לדרך', confirmSub: 'התלמיד יקבל עדכון שאתה בדרך' },
      arrive: { label: 'התחלתי שיעור', emoji: '📚', icon: 'book', confirmTitle: 'תחילת שיעור', confirmSub: 'התלמיד יקבל עדכון שהשיעור התחיל' },
      done: { label: 'סיימתי שיעור', emoji: '✅', icon: 'check', confirmTitle: 'אישור סיום שיעור', confirmSub: 'התלמיד יקבל עדכון שהשיעור הסתיים ויוכל לאשר תשלום' },
    },
    proofLabel: 'עדכון סיום',
    proofSub: 'תעד את סיום השיעור — מוצג לתלמיד',
    rating: {
      ownerHeader: (name) => `איך היה השיעור עם ${name}?`,
      workerHeader: 'דרג את התלמיד',
      ownerSub: 'הביקורת שלך עוזרת לתלמידים אחרים לדעת למה לצפות',
      workerSub: 'הביקורת תעזור לתלמיד לדעת איך להשתפר',
      ownerChipsLabel: 'מה היה טוב בשיעור? (לא חובה)',
      workerChipsLabel: 'איך היה התלמיד?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע בזמן' },
        { key: 'professional', label: '🧠 ידעני ומסביר' },
        { key: 'goodCommunication', label: '💬 תקשורת טובה' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אזמין שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע מוכן' },
        { key: 'goodCommunication', label: '💬 הקשיב והשתתף' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אלמד שוב' },
      ],
      ownerConfirmTitle: '✅ השיעור עבר בהצלחה',
      ownerConfirmSub: 'אשר שהשיעור התקיים כמוסכם והתשלום יבוצע',
      workerConfirmTitle: '✅ סיימתי את השיעור בהצלחה',
      workerConfirmSub: 'אשר שסיימת את השיעור והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שהשיעור עבר בהצלחה',
      workerErrorToast: 'יש לאשר שסיימת את השיעור',
    },
  },

  // ── Creative: photography, events ──
  creative: {
    statusMap: {
      on_the_way: { label: 'בדרך', ownerLabel: 'בדרך אליך', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'התחיל צילום/ביצוע', ownerLabel: 'בביצוע', step: 1 },
      starting: { label: 'בביצוע', ownerLabel: 'בביצוע', step: 1 },
      finishing: { label: 'מסיים', ownerLabel: 'מסיים', step: 1 },
      done: { label: 'סיים — מוסר חומרים', ownerLabel: 'סיים — ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'בדרך', icon: 'navigation' },
      { label: 'בביצוע', icon: 'camera' },
      { label: 'סיום', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לדרך', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לדרך', confirmSub: 'הלקוח יקבל עדכון שאתה בדרך' },
      arrive: { label: 'התחלתי צילום/ביצוע', emoji: '📸', icon: 'camera', confirmTitle: 'תחילת ביצוע', confirmSub: 'הלקוח יקבל עדכון שהעבודה התחילה' },
      done: { label: 'סיימתי + מוסר חומרים', emoji: '✅', icon: 'check', confirmTitle: 'אישור סיום ומסירה', confirmSub: 'הלקוח יקבל עדכון שהעבודה הסתיימה והחומרים מועברים' },
    },
    proofLabel: 'מסירת חומרים',
    proofSub: 'העלה תמונות/סרטונים שצולמו — מוצגים ללקוח',
    rating: {
      ownerHeader: (name) => `איך היה הצילום/האירוע עם ${name}?`,
      workerHeader: 'דרג את הלקוח',
      ownerSub: 'הביקורת שלך עוזרת ללקוחות אחרים לדעת למה לצפות',
      workerSub: 'הביקורת תעזור ללקוח לשפר את החוויה למצלמים הבאים',
      ownerChipsLabel: 'מה היה טוב? (לא חובה)',
      workerChipsLabel: 'איך היה הלקוח?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע בזמן' },
        { key: 'professional', label: '🎨 יצירתיות ואיכות' },
        { key: 'goodCommunication', label: '💬 תקשורת טובה' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אשכור שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ היה מוכן בזמן' },
        { key: 'goodCommunication', label: '💬 בריף ברור' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אצלם שוב' },
      ],
      ownerConfirmTitle: '✅ העבודה בוצעה והחומרים נמסרו',
      ownerConfirmSub: 'אשר שהחומרים נמסרו לשביעות רצונך והתשלום יבוצע כמוסכם',
      workerConfirmTitle: '✅ סיימתי ומסרתי את החומרים',
      workerConfirmSub: 'אשר שסיימת את העבודה ומסרת את החומרים, והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שהחומרים נמסרו לשביעות רצונך',
      workerErrorToast: 'יש לאשר שסיימת ומסרת את החומרים',
    },
  },

  // ── Moving: moving, heavy_lifting ──
  moving: {
    statusMap: {
      on_the_way: { label: 'בדרך', ownerLabel: 'בדרך אליך', step: 0 },
      delayed: { label: 'מתעכב', ownerLabel: 'מתעכב', step: 0 },
      parking: { label: 'מחפש חניה', ownerLabel: 'מחפש חניה', step: 0 },
      arrived: { label: 'התחיל טעינה', ownerLabel: 'בטעינה', step: 1 },
      starting: { label: 'בטעינה', ownerLabel: 'בטעינה', step: 1 },
      finishing: { label: 'בפריקה', ownerLabel: 'בפריקה', step: 1 },
      done: { label: 'סיים פריקה — ממתין לאישור', ownerLabel: 'סיים — ממתין לאישורך', step: 2 },
    },
    steps: [
      { label: 'בדרך', icon: 'navigation' },
      { label: 'טעינה', icon: 'package' },
      { label: 'סיים', icon: 'check' },
    ],
    actions: {
      start: { label: 'יצאתי לדרך', emoji: '🚀', icon: 'navigation', confirmTitle: 'יוצא לדרך', confirmSub: 'הלקוח יקבל עדכון שאתה בדרך' },
      arrive: { label: 'התחלתי טעינה', emoji: '📦', icon: 'package', confirmTitle: 'תחילת טעינה', confirmSub: 'הלקוח יקבל עדכון שהטעינה התחילה' },
      done: { label: 'סיימתי פריקה', emoji: '✅', icon: 'check', confirmTitle: 'אישור סיום פריקה', confirmSub: 'הלקוח יקבל עדכון שהפריקה הסתיימה ויוכל לאשר תשלום' },
    },
    proofLabel: 'הוכחת ביצוע',
    proofSub: 'תמונות לפני/אחרי ההובלה — מוצגות ללקוח',
    rating: {
      ownerHeader: (name) => `איך הייתה ההובלה עם ${name}?`,
      workerHeader: 'דרג את הלקוח',
      ownerSub: 'הביקורת שלך עוזרת למשפחות אחרות לדעת למה לצפות',
      workerSub: 'הביקורת תעזור ללקוח לשפר את החוויה למובילים הבאים',
      ownerChipsLabel: 'מה היה טוב בהובלה? (לא חובה)',
      workerChipsLabel: 'איך היה הלקוח?',
      ownerChips: [
        { key: 'arrivedOnTime', label: '⏱️ הגיע בזמן' },
        { key: 'professional', label: '📦 זהירות בחפצים' },
        { key: 'goodCommunication', label: '💬 תקשורת טובה' },
        { key: 'fairPricing', label: '💰 מחיר הוגן' },
        { key: 'wouldHireAgain', label: '🔁 אשתמש שוב' },
      ],
      workerChips: [
        { key: 'arrivedOnTime', label: '⏱️ היה מוכן בזמן' },
        { key: 'goodCommunication', label: '💬 הסבר ברור מה להוביל' },
        { key: 'fairPricing', label: '💰 שילם כמוסכם' },
        { key: 'wouldHireAgain', label: '🔁 אוביל שוב' },
      ],
      ownerConfirmTitle: '✅ ההובלה בוצעה לשביעות רצוני',
      ownerConfirmSub: 'אשר שכל החפצים הגיעו שלמים והתשלום יבוצע כמוסכם',
      workerConfirmTitle: '✅ סיימתי את ההובלה בהצלחה',
      workerConfirmSub: 'אשר שסיימת את ההובלה והתשלום יתקבל כמוסכם',
      ownerErrorToast: 'יש לאשר שההובלה הושלמה כראוי',
      workerErrorToast: 'יש לאשר שסיימת את ההובלה',
    },
  },
};

export const CATEGORY_WORKFLOW = {
  plumbing: 'onsite_service',
  electricity: 'onsite_service',
  handyman: 'onsite_service',
  cleaning: 'onsite_service',
  carpentry: 'onsite_service',
  ac: 'onsite_service',
  locksmith: 'onsite_service',
  painting: 'onsite_service',
  gardening: 'onsite_service',
  home_maintenance: 'onsite_service',
  it_support: 'onsite_service',
  personal_help: 'onsite_service',
  car: 'onsite_service',
  other: 'onsite_service',
  delivery: 'delivery',
  transportation: 'delivery',
  shopping: 'delivery',
  babysitting: 'care',
  elderly_care: 'care',
  pets: 'care',
  tutoring: 'session',
  fitness: 'session',
  photography: 'creative',
  events: 'creative',
  moving: 'moving',
  heavy_lifting: 'moving',
};

export function getCategoryConfig(category) {
  const type = CATEGORY_WORKFLOW[category] || 'onsite_service';
  return WORKFLOW_TYPES[type] || WORKFLOW_TYPES.onsite_service;
}