import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';

// Native OAuth token handshake.
//
// On mobile (Capacitor) we open OAuth in the system browser. After auth the
// backend redirects to /auth-callback (loaded in the external browser), which
// calls this function with action='store' to persist the access_token keyed by
// a random `sid`. The native app polls action='poll' with the same sid until
// the token arrives, then reloads to authenticate.
//
// This avoids relying on the `joba24://` custom scheme, which is registered in
// the iOS Info.plist but cannot be registered in the Android manifest (Base44
// builds Android and the manifest isn't editable). The server handshake works
// identically on both platforms.
export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json().catch(() => ({}));
    const { action, sid, token } = body || {};
    // sid is the unique per-login-attempt identifier generated by
    // LoginPromptModal. The poll action matches by sid ONLY — there is no
    // fallback. If the backend drops the sid from from_url (causing a null-sid
    // store), the poll simply returns null (login fails gracefully — the user
    // retries) rather than risk returning another user's token.
    const sidStr = typeof sid === 'string' && sid.length >= 8 ? sid : null;

    if (action === 'store') {
      if (!token || typeof token !== 'string') {
        return Response.json({ error: 'invalid token' }, { status: 400 });
      }
      // Cleanup expired handshake records (older than 10 minutes).
      const tenMinAgo = new Date(Date.now() - 10 * 60 * 1000).toISOString();
      try {
        await base44.asServiceRole.entities.OAuthHandshake.deleteMany({ created_date: { $lt: tenMinAgo } });
      } catch {}
      // Replace any existing record for this sid (idempotent retries).
      if (sidStr) {
        try {
          await base44.asServiceRole.entities.OAuthHandshake.deleteMany({ sid: sidStr });
        } catch {}
      }
      await base44.asServiceRole.entities.OAuthHandshake.create({ sid: sidStr, token });
      return Response.json({ ok: true });
    }

    if (action === 'poll') {
      // Match by sid ONLY. The sid is unique per login attempt (generated in
      // LoginPromptModal), so this can never return another user's token.
      //
      // The previous "most recent sid=null record" fallback was a CRITICAL
      // security hole: the OAuthHandshake table is global (not device-scoped),
      // so when the backend dropped the sid from from_url, the fallback
      // returned the most recent null-sid record from ANY user/device —
      // logging user B into user A's account (cross-user contamination). The
      // sid is now reliably preserved via the base44.app from_url
      // (LoginPromptModal hardcodes it), so the fallback is unnecessary.
      // If the sid is missing or unmatched, return null (login fails
      // gracefully — the user retries) rather than risk the wrong user's token.
      if (sidStr) {
        const bySid = await base44.asServiceRole.entities.OAuthHandshake.filter({ sid: sidStr }, '-created_date', 1);
        const rec = bySid && bySid[0];
        if (rec) {
          try { await base44.asServiceRole.entities.OAuthHandshake.delete(rec.id); } catch {}
          return Response.json({ token: rec.token });
        }
      }
      return Response.json({ token: null });
    }

    return Response.json({ error: 'invalid action' }, { status: 400 });
  } catch (error) {
    return Response.json({ error: (error as Error).message }, { status: 500 });
  }
}