// Auto-generated es translations
const es = {
  '🔧 אינסטלציה': '🔧 Fontanería',
  '⚡ חשמלאות': '⚡ Electricidad',
  '🌿 גינון': '🌿 Jardinería',
  '🧹 ניקיון': '🧹 Limpieza',
  '🚛 הובלה': '🚛 Mudanzas',
  '🎨 צביעה': '🎨 Pintura',
  '🪵 נגרות': '🪵 Carpintería',
  '❄️ מזגנים': '❄️ Aire acondicionado',
  '🔐 מנעולן': '🔐 Cerrajería',
  '🛒 קניות': '🛒 Compras',
  '📦 משלוח': '📦 Envíos',
  '👶 בייביסיטר': '👶 Niñera',
  '📚 שיעורים פרטיים': '📚 Clases particulares',
  '💻 מחשבים': '💻 Computadoras',
  '🔨 הנדימן / תיקונים': '🔨 Handyman / Reparaciones',
  '💪 עזרה פיזית': '💪 Ayuda física',
  '🏠 תחזוקת בית': '🏠 Mantenimiento del hogar',
  '🚗 הסעות וטרמפים': '🚗 Transporte y viajes',
  '🐶 בעלי חיים': '🐶 Mascotas',
  '👵 סיוע לקשישים': '👵 Asistencia a personas mayores',
  '🏋️ כושר וספורט': '🏋️ Fitness y deporte',
  '📸 צילום ותוכן': '📸 Fotografía y contenido',
  '🎉 אירועים': '🎉 Eventos',
  '🤝 עזרה אישית': '🤝 Asistencia personal',
  '🚗 רכב': '🚗 Vehículo',
  '📋 אחר': '📋 Otro',
  'מה הבעיה? 🔧 (ניתן לבחור יותר מאחת)': '¿Cuál es el problema? 🔧 (puede elegir más de una)',
  'איפה בבית? (ניתן לבחור כמה)': '¿En qué parte de la casa? (puede elegir varias)',
  '🚨 יש זרימת מים פעילה עכשיו (נזק מתרחש)': '🚨 Hay una fuga de agua activa ahora (está causando daños)',
  'יודע איפה ברז המים הראשי': 'Sabe dónde está la llave de paso principal del agua',
  'מה צריך? ⚡ (ניתן לבחור יותר מאחת)': '¿Qué necesita? ⚡ (puede elegir más de una)',
  '🚨 אין חשמל עכשיו בכל הבית / בחלקו': '🚨 No hay electricidad ahora en toda la casa / en parte de ella',
  'אילו חדרים מושפעים?': '¿Qué habitaciones están afectadas?',
  'לוח החשמל מעודכן ובעל היתר': 'El cuadro eléctrico está actualizado y tiene permiso',
  'מה צריך לעשות? 🌿 (ניתן לבחור יותר מאחת)': '¿Qué se debe hacer? 🌿 (puede elegir más de una)',
  'גודל הגינה': 'Tamaño del jardín',
  'איזה סוג גינה?': '¿Qué tipo de jardín?',
  'צריך לפנות פסולת / ענפים': 'Necesita retirar desechos / ramas',
  'יש ציוד בבית (מקצרה, מסור, גזם...)': 'Tiene equipo en casa (cortacésped, sierra, podadora...)',
  'חד-פעמי או טיפול שוטף?': '¿Es un servicio único o recurrente?',
  'איזה סוג ניקיון? 🧹 (ניתן לבחור יותר מאחת)': '¿Qué tipo de limpieza? 🧹 (puede elegir más de una)',
  'מה מנקים?': '¿Qué se limpia?',
  'כמה חדרים? (לא כולל מטבח ושירותים)': '¿Cuántas habitaciones? (sin incluir cocina y baños)',
  'כמה חדרי אמבטיה / שירותים?': '¿Cuántos baños / aseos?',
  'יש חומרי ניקוי בבית': 'Tiene productos de limpieza en casa',
  'יש ציוד (שואב אבק, מגב...)': 'Tiene equipo (aspiradora, fregona...)',
  'חד-פעמי או קבוע?': '¿Es único o constante?',
  'מתי להגיע? 📅': '¿Cuándo llegar? 📅',
  'כתובת יעד — לאן מובילים? *': 'Dirección de destino — ¿A dónde llevar? *',
  'מה מובילים?': '¿Qué se transporta?',
  'קומה במוצא': 'Piso de origen',
  'קומה ביעד': 'Piso de destino',
  'יש מעלית במוצא': 'Hay ascensor en el origen',
  'יש מעלית ביעד': 'Hay ascensor en el destino',
  'איזה רכב צריך?': '¿Qué vehículo se necesita?',
  'צריך עזרה באריזה': 'Necesita ayuda con el embalaje',
  'צריך לפרק ולהרכיב רהיטים': 'Necesita desmontar y montar muebles',
  'תיאור הפריטים (לא חובה)': 'Descripción de los artículos (opcional)',
  'מה צריך לצבוע? (ניתן לבחור יותר מאחד)': '¿Qué necesita pintar? (puede elegir más de una)',
  'כמה חדרים / קירות?': '¿Cuántas habitaciones / paredes?',
  'שטח משוער (מ"ר)': 'Área estimada (m²)',
  'יש צבע (לא צריך להביא)': 'Tiene pintura (no necesita traer)',
  'צריך הכנה — טיח / גבס / סתימת סדקים': 'Necesita preparación — yeso / placas de yeso / sellado de grietas',
  'מצב הקירות': 'Estado de las paredes',
  'איזה הכנה צריך?': '¿Qué preparación necesita?',
  'מה צריך? 🪵 (ניתן לבחור יותר מאחת)': '¿Qué necesita? 🪵 (puede elegir más de una)',
  'כמה פריטים?': '¿Cuántos artículos?',
  'מותג הריהוט (אם רלוונטי)': 'Marca del mueble (si aplica)',
  'יש כלים בבית (מקדחה, פטיש...)': 'Tiene herramientas en casa (taladro, martillo...)',
  'יש הוראות הרכבה / שרטוט': 'Tiene instrucciones de montaje / plano',
  'מה צריך? ❄️': '¿Qué necesita? ❄️',
  'כמה יחידות?': '¿Cuántas unidades?',
  'סוג מזגן': 'Tipo de aire acondicionado',
  'גיל המזגן': 'Edad del aire acondicionado',
  'צריך הרכבה על הקיר (תליית יחידה פנימית)': 'Necesita montaje en pared (colgar unidad interna)',
  'גישה ליחידה החיצונית': 'Acceso a la unidad externa',
  'מה הבעיה? 🔐': '¿Cuál es el problema? 🔐',
  '🚨 ננעלתי בחוץ כרגע — זה דחוף מאוד': '🚨 Estoy encerrado afuera en este momento — es muy urgente',
  'סוג הדלת': 'Tipo de puerta',
  'סוג המנעול (אם ידוע)': 'Tipo de cerradura (si se conoce)',
  'מה קונים? 🛒 (ניתן לבחור יותר מאחד)': 'מה קונים? 🛒 (ניתן לבחור יותר מאחד)',
  'שם החנות / מיקום': 'Nombre de la tienda / ubicación',
  'תקציב הקנייה (₪) משוער': 'Presupuesto estimado de compra (₪)',
  'רשימת קניות': 'Lista de la compra',
  'צריך להביא קבלה': 'Debe traer el recibo',
  'איך נשלם על הקנייה?': '¿Cómo pagaremos la compra?',
  'כתובת מסירה — לאן? *': 'Dirección de entrega — ¿A dónde? *',
  'מה מוסרים?': '¿Qué se entrega?',
  'מתי צריך להגיע?': '¿Cuándo debe llegar?',
  'שם המקבל (לא חובה)': 'Nombre del destinatario (opcional)',
  'טלפון המקבל (לא חובה)': 'Teléfono del destinatario (opcional)',
  'שביר — יש לטפל בזהירות': 'Frágil — manipular con cuidado',
  'צריך שמירה על קור (קירור)': 'Requiere refrigeración',
  'כמה ילדים?': '¿Cuántos niños?',
  'גילאי הילדים': 'Edades de los niños',
  'מתי נדרשת הבייביסיטר? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita la niñera? 📅 (fecha y horas exactas)',
  'איפה?': '¿Dónde?',
  'מה נדרש לעשות? (ניתן לבחור כמה)': '¿Qué se requiere hacer? (puede elegir varias)',
  'צרכים מיוחדים / אלרגיות / מידע חשוב': 'Necesidades especiales / alergias / información importante',
  'יש חיות מחמד בבית': 'Hay mascotas en casa',
  'פרטי חיות המחמד': 'Detalles de las mascotas',
  'נדרש ניסיון בעזרה ראשונה / החייאה': 'Se requiere experiencia en primeros auxilios / reanimación',
  'מעשנים בבית': 'Se fuma en la casa',
  'איזה מקצוע? 📚': '¿Qué materia? 📚',
  'כיתה / רמה': 'Curso / nivel',
  'מתי נדרש השיעור? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita la clase? 📅 (fecha y horas exactas)',
  'פרונטלי או אונליין?': '¿Presencial u online?',
  'מטרה / תיאור (לא חובה)': 'Objetivo / descripción (opcional)',
  'יש לקות למידה / ADHD (נדרשת התאמה)': 'Tiene dificultades de aprendizaje / TDAH (se requiere adaptación)',
  'מה הבעיה? 💻 (ניתן לבחור יותר מאחת)': '¿Cuál es el problema? 💻 (puede elegir más de una)',
  'איזה מכשיר?': '¿Qué dispositivo?',
  'מערכת הפעלה (אם ידוע)': 'Sistema operativo (si se conoce)',
  'איך מועדף?': '¿Cómo prefiere?',
  '⚠️ יש נתונים חשובים שעלולים לאבד': '⚠️ Hay datos importantes que podrían perderse',
  'מה צריך לעשות? 🔨 (ניתן לבחור יותר מאחת)': '¿Qué se debe hacer? 🔨 (puede elegir más de una)',
  'סוג הקיר (אם רלוונטי)': 'Tipo de pared (si aplica)',
  'כמה עבודות / פריטים?': '¿Cuántos trabajos / artículos?',
  'מה צריך? 💪': '¿Qué necesita? 💪',
  'מה מזיזים?': '¿Qué se traslada?',
  'משקל משוער לפריט': 'Peso estimado por artículo',
  'קומה (אם רלוונטי)': 'Piso (si aplica)',
  'כמה עוזרים צריך?': '¿Cuántos ayudantes se necesitan?',
  'מה צריך? 🏠 (ניתן לבחור יותר מאחת)': '¿Qué necesita? 🏠 (puede elegir más de una)',
  'גודל השטח / היקף העבודה': 'Tamaño del área / alcance del trabajo',
  'צריך לפנות / להשליך ציוד': 'Necesita retirar / desechar equipo',
  'מה מפנים?': '¿Qué se retira?',
  'איזה סוג נסיעה? 🚗': '¿Qué tipo de viaje? 🚗',
  'לאן נוסעים? *': '¿A dónde va? *',
  'כמה נוסעים?': '¿Cuántos pasajeros?',
  'יש כבודה גדולה / מזוודות': 'Tiene equipaje grande / maletas',
  'כמה מזוודות?': '¿Cuántas maletas?',
  'צריך כיסא בטיחות לילד': 'Necesita silla de seguridad para niños',
  'כמה כיסאות בטיחות?': '¿Cuántas sillas de seguridad?',
  'מה צריך? 🐶': '¿Qué necesita? 🐶',
  'איזה חיה?': '¿Qué animal?',
  'גודל הכלב': 'Tamaño del perro',
  'גזע הכלב (אם ידוע)': 'Raza del perro (si se conoce)',
  'גיל הכלב': 'Edad del perro',
  'אופי הכלב — ניתן לבחור כמה': 'Carácter del perro — puede elegir varios',
  'הכלב מסתדר עם כלבים אחרים?': '¿El perro se lleva bien con otros perros?',
  'מחוסן ומעודכן': 'Vacunado y al día',
  'מסורס / מעוקר': 'Castrado / esterilizado',
  'בית עם ילדים': 'Hogar con niños',
  'בית עם חתולים': 'Hogar con gatos',
  'חתול ביתי (לא יוצא החוצה)': 'Gato doméstico (no sale)',
  'צריך החלפת חול / ניקוי ארגז': 'Necesita cambio de arena / limpieza de caja',
  'מתי נדרש השירות? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita el servicio? 📅 (fecha y horas exactas)',
  'הוראות האכלה / תרופות': 'Instrucciones de alimentación / medicamentos',
  'צרכים מיוחדים / מצב רפואי': 'Necesidades especiales / estado médico',
  'העובד יקבל מפתח לבית': 'El trabajador recibirá una llave de la casa',
  'מה צריך? 👵 (ניתן לבחור יותר מאחת)': '¿Qué necesita? 👵 (puede elegir más de una)',
  'מתי נדרש הסיוע? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita la asistencia? 📅 (fecha y horas exactas)',
  'מצב הניידות של הקשיש': 'Estado de movilidad de la persona mayor',
  'הקשיש צריך הסעה (יש רכב משלו או שצריך רכב של העובד)': 'La persona mayor necesita transporte (¿tiene su propio vehículo o necesita el vehículo del trabajador?)',
  'לקשיש יש רכב משלו': 'La persona mayor tiene su propio vehículo',
  'מצב קוגניטיבי (אם רלוונטי)': 'Estado cognitivo (si aplica)',
  'נדרש תזכורת / עזרה בנטילת תרופות': 'Se requiere recordatorio / ayuda en la toma de medicamentos',
  'שפה מועדפת (אם רלוונטי)': 'Idioma preferido (si aplica)',
  'איזה אימון? 🏋️ (ניתן לבחור יותר מאחד)': 'איזה אימון? 🏋️ (ניתן לבחור יותר מאחד)',
  'רמת הכושר שלך': 'Su nivel de forma física',
  'מתי נדרש האימון? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita el entrenamiento? 📅 (fecha y horas exactas)',
  'מטרה (לא חובה)': 'Objetivo (opcional)',
  'מגבלות רפואיות / פציעות (לא חובה)': 'Limitaciones médicas / lesiones (opcional)',
  'יש ציוד בבית (משקולות, מזרון...)': 'Tiene equipo en casa (pesas, colchoneta...)',
  'מה צריך? 📸 (ניתן לבחור יותר מאחד)': 'מה צריך? 📸 (ניתן לבחור יותר מאחד)',
  'כמה זמן?': '¿Cuánto tiempo?',
  'צריך עריכה + תמונות/סרטונים מוגמרים': 'Necesita edición + fotos/videos finales',
  'איזה עריכה?': '¿Qué tipo de edición?',
  'צריך צילום רחפן': 'Necesita fotografía con dron',
  'כמה תמונות / סרטונים סופיים צריך?': '¿Cuántas fotos / videos finales necesita?',
  'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)': 'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)',
  'סוג האירוע': 'Tipo de evento',
  'כמה אורחים?': '¿Cuántos invitados?',
  'כמה שעות?': '¿Cuántas horas?',
  'נדרש מדים / תלבושת אחידה': 'Se requiere uniforme',
  'מה צריך? 🤝 (ניתן לבחור יותר מאחד)': 'מה צריך? 🤝 (ניתן לבחור יותר מאחד)',
  'מתי נדרשת העזרה? 📅 (תאריך ושעות מדויקים)': '¿Cuándo se necesita la ayuda? 📅 (fecha y horas exactas)',
  'צריך רכב משל העובד': 'Necesita el vehículo del trabajador',
  'מערב ילדים (איסוף / הסעה)': 'Involucra niños (recogida / transporte)',
  'מה צריך? 🚗 (ניתן לבחור יותר מאחת)': '¿Qué necesita? 🚗 (puede elegir más de una)',
  'איזו תקלה? (אם יש)': '¿Qué avería? (si hay alguna)',
  'יצרן הרכב': 'Fabricante del vehículo',
  'שנתון הרכב': 'Año del vehículo',
  'איפה הרכב כעת?': '¿Dónde está el vehículo ahora?',
  '🚨 צריך גרירה / הובלת הרכב': '🚨 Necesita grúa / transporte del vehículo',
  'יש חלקי חילוף (לא צריך להביא)': 'Tiene piezas de repuesto (no necesita traer)',
  'הערות נוספות (לא חובה)': 'Notas adicionales (opcional)',
  'נזילה ממקור מסוים': 'Fuga de un origen específico',
  'סתימה בכיור / אמבטיה / שירותים': 'Obstrucción en fregadero / bañera / inodoro',
  'החלפת ברז': 'Cambio de grifo',
  'אסלה שלא מפסיקה לזרום': 'Inodoro que no deja de perder agua',
  'דוד שמש / בוילר': 'Calentador solar / termo eléctrico',
  'התקנת מכשיר חדש (מדיח, מכונת כביסה)': 'Instalación de aparato nuevo (lavavajillas, lavadora)',
  'ריח / ביוב עולה': 'Mal olor / aguas residuales subiendo',
  'בדיקה כללית': 'Inspección general',
  'מטבח': 'Cocina',
  'חדר אמבטיה': 'Cuarto de baño',
  'שירותים': 'Aseos',
  'מרפסת': 'Balcón',
  'מחוץ לבית': 'Fuera de la casa',
  'שקע / מפסק לא עובד': 'Enchufe / interruptor no funciona',
  'נפילת חשמל (מפסק קפץ)': 'Corte de luz (saltó el interruptor)',
  'התקנת שקע חדש': 'Instalación de enchufe nuevo',
  'החלפת נורה / גוף תאורה': 'Cambio de bombilla / luminaria',
  'בדיקת לוח חשמל': 'Revisión del cuadro eléctrico',
  'חיווט לחדר / מקום חדש': 'Cableado para una habitación / lugar nuevo',
  'התקנת מאוורר תקרה': 'Instalación de ventilador de techo',
  'חיווט לדוד / למזגן': 'Cableado para calentador / aire acondicionado',
  'סלון': 'Sala de estar',
  'חדר שינה': 'Dormitorio',
  'כל הבית': 'Toda la casa',
  'כיסוח דשא': 'Corte de césped',
  'גיזום עצים / שיחים': 'Poda de árboles / arbustos',
  'עישוב (ניכוש עשבים)': 'Deshierbe',
  'ניקוי וסידור הגינה': 'Limpieza y orden del jardín',
  'פינוי ענפים / גזם': 'Retirada de ramas / restos de poda',
  'שתילה / הקמת ערוגה': 'Plantación / creación de parterre',
  'תכנון והקמת גינה חדשה': 'Diseño y creación de jardín nuevo',
  'תיקון מערכת השקיה': 'Reparación del sistema de riego',
  'קטנה — עד 20 מ"ר': 'Pequeño — hasta 20 m²',
  'בינונית — 20–60 מ"ר': 'Mediano — 20–60 m²',
  'גדולה — 60–150 מ"ר': 'Grande — 60–150 m²',
  'גדולה מאוד — מעל 150 מ"ר': 'Muy grande — más de 150 m²',
  'גינה פרטית בבית': 'Jardín privado en casa',
  'גינת בניין משותף': 'Jardín comunitario de edificio',
  'מרפסת / גג': 'Balcón / azotea',
  'שטח ציבורי / עסקי': 'Área pública / comercial',
  'חד-פעמי': 'Único',
  'שבועי': 'Semanal',
  'דו-שבועי': 'Quincenal',
  'חודשי': 'Mensual',
  'ניקיון שוטף (שבועי / דו-שבועי)': 'Limpieza rutinaria (semanal / quincenal)',
  'ניקוי עומק (אחת לחודש)': 'Limpieza a fondo (una vez al mes)',
  'ניקיון לפני / אחרי מעבר דירה': 'Limpieza antes / después de mudanza',
  'ניקיון לאחר שיפוץ': 'ניקיון לאחר שיפוץ',
  'ניקוי חלונות': 'Limpieza de ventanas',
  'ניקוי שטיחים / ריפוד': 'Limpieza de alfombras / tapicería',
  'ניקוי מטבח / תנור': 'Limpieza de cocina / horno',
  'ניקוי משרד / עסק': 'Limpieza de oficina / negocio',
  'דירה': 'Apartamento',
  'בית פרטי': 'Casa privada',
  'משרד': 'Oficina',
  'מחסן / חדר': 'Trastero / habitación',
  'מעבר דירה מלא': 'Mudanza completa',
  'כמה פריטים / ארגזים': '¿Cuántos artículos / cajas?',
  'רהיט בודד (ספה, מיטה, ארון)': 'Mueble individual (sofá, cama, armario)',
  'ציוד / מכשיר גדול': 'Equipo / aparato grande',
  'טנדר / סטיישן מספיק': 'Furgoneta / familiar suficiente',
  'ואן בינוני': 'Furgoneta mediana',
  'משאית קטנה': 'Camión pequeño',
  'משאית גדולה': 'Camión grande',
  'לא בטוח': 'No estoy seguro',
  'קירות פנים (חדר / דירה)': 'Paredes interiores (habitación / apartamento)',
  'תקרה': 'Techo',
  'קירות חוץ': 'Paredes exteriores',
  'גדר / קיר חיצוני': 'Valla / muro exterior',
  'דלת / חלון': 'Puerta / ventana',
  'ריהוט עץ': 'Muebles de madera',
  'מדרגות': 'Escaleras',
  'חדש — רק צבע': 'Nuevo — solo pintura',
  'תקין — צריך שכבה': 'En buen estado — necesita una capa',
  'דורש תיקון קל': 'Requiere reparación leve',
  'דורש שיפוץ מקדים': 'Requiere reforma previa',
  'טיח / מריחת גבס': 'Enlucido / aplicado de yeso',
  'סתימת סדקים': 'Sellado de grietas',
  'הסרת טפט ישן': 'Retirada de papel pintado viejo',
  'שיוף קיר ישן': 'Lijado de pared vieja',
  'תיקון רטיבות': 'Reparación de humedad',
  'תיקון / חיזוק רהיט שבור': 'Reparación / refuerzo de mueble roto',
  'בניית מדף / ארון מותאם': 'Construcción de estante / armario a medida',
  'החלפת / תיקון דלת': 'Cambio / reparación de puerta',
  'התקנת מטבח / ארונות': 'Instalación de cocina / armarios',
  'עבודת עץ מותאמת אישית': 'Carpintería personalizada',
  'פירוק רהיטים': 'Desmontaje de muebles',
  'פריט אחד': 'Un artículo',
  '2–3 פריטים': '2–3 artículos',
  '4–6 פריטים': '4–6 artículos',
  'יותר מ-6': 'Más de 6',
  'הום סנטר': 'Home Center',
  'אייס': 'Ace',
  'לא רלוונטי': 'No aplica',
  'התקנת מזגן חדש': 'Instalación de aire acondicionado nuevo',
  'פירוק מזגן': 'Desmontaje de aire acondicionado',
  'ניקוי / שירות שנתי': 'Limpieza / mantenimiento anual',
  'מזגן לא מקרר / לא מחמם': 'Aire acondicionado no enfría / no calienta',
  'מזגן מטפטף מים': 'Aire acondicionado gotea agua',
  'מזגן לא נדלק': 'Aire acondicionado no enciende',
  'רעש / רטיט במזגן': 'Ruido / vibración en aire acondicionado',
  'מפוצל (split)': 'Split',
  'נייד': 'Portátil',
  'מיני מרכזי': 'Mini central',
  'מרכזי / תעלות': 'Central / conductos',
  'לא יודע': 'No sé',
  'חדש (עד שנתיים)': 'Nuevo (hasta 2 años)',
  'מעל 7 שנים': 'Más de 7 años',
  'מרפסת / גג נגיש': 'Balcón / azotea accesible',
  'צריך סולם': 'Necesita escalera',
  'צריך בניין / סנפלינג': 'Necesita andamio / rapel (trabajo en altura)',
  '🚨 ננעלתי בחוץ — פריצת מנעול': '🚨 Estoy encerrado fuera — apertura de cerradura',
  'החלפת מנעול': 'Cambio de cerradura',
  'התקנת מנעול חדש / חיזוק': 'Instalación de cerradura nueva / refuerzo',
  'שכפול מפתח': 'Copia de llave',
  'תיקון / ידית דלת': 'Reparación / manilla de puerta',
  'כספת — פתיחה / התקנה': 'Caja fuerte — apertura / instalación',
  'צילינדר חסום / מפתח שבור בפנים': 'Cilindro bloqueado / llave rota dentro',
  'דלת דירה': 'Puerta de apartamento',
  'דלת בית פרטי': 'Puerta de casa privada',
  'דלת מחסן / חניה': 'Puerta de trastero / garaje',
  'דלת משרד': 'Puerta de oficina',
  'מכונית': 'Automóvil',
  'צילינדר רגיל': 'Cilindro estándar',
  'מולטילוק': 'Mul-T-Lock',
  'מנעול חכם / קוד': 'Cerradura inteligente / código',
  'בריח': 'Cerrojo',
  'מזון (סופר / מכולת)': 'Alimentos (supermercado / tienda de comestibles)',
  'תרופות / בית מרקחת': 'Medicamentos / farmacia',
  'פירות וירקות (שוק)': 'Frutas y verduras (mercado)',
  'ציוד / חנות ספציפית': 'Equipo / tienda específica',
  'אלכוהול': 'Alcohol',
  'קניות כלליות — יסופק רשימה': 'Compras generales — se proporcionará una lista',
  'מזומן בחזרה': 'Efectivo (contra reembolso)',
  'העברה בביט': 'Transferencia por Bit',
  'אשראי': 'Tarjeta de crédito',
  'מסמכים / מעטפה': 'Documentos / sobre',
  'חבילה קטנה (כמו נעליים)': 'Paquete pequeño (como zapatos)',
  'חבילה בינונית (כמו מזוודה)': 'Paquete mediano (como una maleta)',
  'חבילה גדולה / כבדה': 'Paquete grande / pesado',
  'אוכל / מזון': 'Comida / alimentos',
  'תרופות': 'Medicamentos',
  '🔴 מיידי — תוך שעה': '🔴 Inmediato — en una hora',
  'היום עד שעה מסוימת': 'Hoy hasta cierta hora',
  'היום — גמיש': 'Hoy — flexible',
  'מחר': 'Mañana',
  'גמיש לחלוטין': 'Completamente flexible',
  'בבית שלנו': 'En nuestra casa',
  'בבית הבייביסיטר': 'En casa de la niñera',
  'גמיש': 'Flexible',
  'שמירה בלבד': 'Solo cuidado',
  'הכנת ארוחה': 'Preparación de comida',
  'השכבה לשינה': 'Poner a dormir',
  'עזרה בשיעורים': 'Ayuda con los deberes',
  'אמבטיה': 'Baño',
  'הסעה / איסוף מגן': 'Transporte / recogida de la guardería',
  'משחק ופעילות': 'Juego y actividad',
  'כיתה א-ו (יסודי)': '1º-6º grado (primaria)',
  'כיתה ז-ט (חטיבה)': '7º-9º grado (secundaria)',
  'כיתה י-יב (תיכון)': '10º-12º grado (bachillerato)',
  'הכנה לבגרות': 'Preparación para selectividad (Bagrut)',
  'אקדמיה / אוניברסיטה': 'Academia / universidad',
  'מבוגר': 'Adulto',
  'פרונטלי — בבית': 'Presencial — en casa',
  'פרונטלי — אצל המורה': 'Presencial — en casa del profesor',
  'זום / אונליין': 'Zoom / online',
  'מחשב איטי מאוד': 'Computadora muy lenta',
  'מחשב לא נדלק': 'Computadora no enciende',
  'וירוס / תוכנה זדונית': 'Virus / malware',
  'בעיית אינטרנט / WiFi': 'Problema de internet / WiFi',
  'התקנת תוכנה / Windows': 'Instalación de software / Windows',
  'גיבוי נתונים / שחזור': 'Copia de seguridad / recuperación de datos',
  'בעיית מסך / מקלדת / עכבר': 'Problema de pantalla / teclado / mouse',
  'הגדרת אימייל / חשבון': 'Configuración de correo electrónico / cuenta',
  'התקנת מדפסת': 'Instalación de impresora',
  'מחשב נייח': 'Computadora de escritorio',
  'לפטופ (נייד)': 'Laptop (portátil)',
  'טאבלט': 'Tablet',
  'סמארטפון': 'Smartphone',
  'ראוטר / רשת': 'Router / red',
  'מדפסת': 'Impresora',
  'כמה מכשירים': '¿Cuántos dispositivos?',
  'ביקור בית / עסק': 'Visita a domicilio / negocio',
  'מרחוק (remote)': 'Remoto',
  'תליית טלוויזיה על קיר': 'Colgar televisor en la pared',
  'תליית מדף / תמונה': 'Colgar estante / cuadro',
  'התקנת וילון / בלינד': 'Instalación de cortina / persiana',
  'החלפת ידית / מנגנון': 'Cambio de manilla / mecanismo',
  'תיקון ריהוט שבור': 'Reparación de mueble roto',
  'הרכבת ריהוט מקופסה': 'Montaje de muebles en caja',
  'איטום / גבס קטן': 'Sellado / pequeño arreglo de yeso',
  'התקנת מנורה / גוף תאורה': 'Instalación de lámpara / luminaria',
  'תיקון דלת / ציר': 'Reparación de puerta / bisagra',
  'בטון / בלוק': 'Hormigón / bloque',
  'גבס': 'Yeso',
  'עבודה אחת': 'Un trabajo',
  '2–3 עבודות': '2–3 trabajos',
  '4 ומעלה': '4 o más',
  'להעלות / להוריד פריט כבד': 'Subir / bajar un artículo pesado',
  'לסחוב ארגזים / קרטונים': 'Cargar cajas / cartones',
  'פריקת משאית / ואן': 'Descarga de camión / furgoneta',
  'עזרה בהזזת ריהוט בתוך הבית': 'Ayuda para mover muebles dentro de la casa',
  'עזרה במעבר דירה (ללא נהג)': 'Ayuda en mudanza (sin conductor)',
  'טעינת פריטים לרכב': 'Carga de artículos en el vehículo',
  'עד 15 ק"ג': 'Hasta 15 kg',
  '15–30 ק"ג': '15–30 kg',
  '30–60 ק"ג': '30–60 kg',
  'מעל 60 ק"ג': 'Más de 60 kg',
  'ארגזים רבים': 'Muchas cajas',
  'קרקע': 'Planta baja',
  'קומה 1': '1er piso',
  'קומה 2': '2do piso',
  'קומה 3+': '3er piso o más',
  'יש מעלית': 'Hay ascensor',
  'אחד מספיק': 'Uno es suficiente',
  'שניים': 'Dos',
  'שלושה ומעלה': 'Tres o más',
  'ניקוי / פינוי מחסן': 'Limpieza / vaciado de trastero',
  'סידור וארגון מחסן': 'Orden y organización de trastero',
  'ניקוי מרזבים / גג': 'Limpieza de canalones / azotea',
  'פינוי פסולת / ריהוט ישן': 'Retirada de desechos / muebles viejos',
  'ניקוי מרפסת / חצר': 'Limpieza de balcón / patio',
  'ארגון בית כללי': 'Organización general de la casa',
  'תיקונים קטנים בבית': 'Pequeñas reparaciones en casa',
  'קטן — עד שעה': 'Pequeño — hasta una hora',
  'בינוני — 2–3 שעות': 'Mediano — 2–3 horas',
  'גדול — חצי יום': 'Grande — medio día',
  'גדול מאוד — יום שלם': 'Muy grande — día completo',
  'ריהוט ישן': 'Muebles viejos',
  'פסולת בניין': 'Escombros',
  'קרטונים': 'Cartones',
  'גזם / ענפים': 'Restos de poda / ramas',
  'ציוד חשמלי': 'Equipo eléctrico',
  'אשפה כללית': 'Basura general',
  'נסיעה לשדה התעופה / ממנו': 'Viaje al aeropuerto / desde él',
  'הסעה לאירוע': 'Transporte a evento',
  'הסעת ילדים (גן / בית ספר / חוגים)': 'Transporte de niños (guardería / escuela / actividades)',
  'טרמפ לעבודה / עיר אחרת': 'Viaje al trabajo / otra ciudad',
  'נהג פרטי לכמה שעות': 'Chofer privado por unas horas',
  'נסיעה לבית חולים / קופת חולים': 'Viaje al hospital / centro médico',
  'הסעת קשיש': 'Transporte de persona mayor',
  '1': '1',
  '1–2': '1–2',
  'טיול עם הכלב': 'Paseo con el perro',
  'שמירה / פנסיון בבית המטפל': 'Cuidado / guardería en casa del cuidador',
  'ביקור יומי (האכלה / השקיה / טיול קצר)': 'Visita diaria (alimentación / riego / paseo corto)',
  'הסעה לוטרינר / טיפוח': 'Transporte al veterinario / peluquería',
  'אילוף / אימון': 'Adiestramiento / entrenamiento',
  'טיפוח / גזיזה / אמבטיה': 'Aseo / corte / baño',
  'כלב': 'Perro',
  'חתול': 'Gato',
  'ארנב / מכרסם': 'Conejo / roedor',
  'ציפור': 'Pájaro',
  'זוחל': 'Reptil',
  'דגים': 'Peces',
  'כמה חיות': '¿Cuántos animales?',
  'קטן — עד 10 ק"ג': 'Pequeño — hasta 10 kg',
  'בינוני — 10–25 ק"ג': 'Mediano — 10–25 kg',
  'גדול — 25–45 ק"ג': 'Grande — 25–45 kg',
  'ענק — מעל 45 ק"ג': 'Gigante — más de 45 kg',
  'גור (עד שנה)': 'Cachorro (hasta 1 año)',
  'צעיר (1–3 שנים)': 'Joven (1–3 años)',
  'בוגר (3–7 שנים)': 'Adulto (3–7 años)',
  'מבוגר (מעל 7)': 'Mayor (más de 7)',
  'ידידותי': 'Amigable',
  'רגוע': 'Tranquilo',
  'אנרגטי': 'Enérgico',
  'חרדתי': 'Ansioso',
  'תקיף / תוקפני': 'Agresivo',
  'מושך ברצועה': 'Tira de la correa',
  'בורח לפעמים': 'Se escapa a veces',
  'כן, ידידותי': 'Sí, es amigable',
  'בסדר עם היכרות': 'Bien si se le presenta',
  'מסתייג': 'Receloso',
  'ליווי לרופא / קופת חולים': 'Acompañamiento al médico / centro de salud',
  'ליווי לבית מרקחת / קניות': 'Acompañamiento a farmacia / compras',
  'קניות עבור הקשיש': 'Compras para la persona mayor',
  'עזרה בבית (כביסה, ניקיון קל)': 'Ayuda en casa (lavandería, limpieza ligera)',
  'חברה וביקור (שיחה, הליכה)': 'Compañía y visitas (conversación, paseo)',
  'עזרה בטכנולוגיה (טלפון, מחשב)': 'Ayuda tecnológica (teléfono, computadora)',
  'עזרה בטפסים / ביורוקרטיה': 'Ayuda con formularios / burocracia',
  'הכנת ארוחה': 'Preparación de comida',
  'הולך באופן עצמאי': 'Camina de forma independiente',
  'זקוק לעזרה בהליכה / תמיכה': 'Necesita ayuda para caminar / apoyo',
  'מרותק לכיסא גלגלים': 'En silla de ruedas',
  'מרותק למיטה': 'Postrado en cama',
  'צלול ועצמאי': 'Lúcido e independiente',
  'זיכרון ירוד קל': 'Leve pérdida de memoria',
  'דמנציה / אלצהיימר': 'Demencia / Alzheimer',
  'אימון כושר כללי': 'Entrenamiento físico general',
  'ריצה / הכנה לריצה': 'Running / preparación para correr',
  'יוגה': 'Yoga',
  'פילאטיס': 'Pilates',
  'אימון כוח / הרמת משקולות': 'Entrenamiento de fuerza / pesas',
  'אימון בית (ללא ציוד)': 'Entrenamiento en casa (sin equipo)',
  'אימון בחדר כושר': 'Entrenamiento en gimnasio',
  'שחייה': 'Natación',
  'אימון תפקודי / שיקום': 'Entrenamiento funcional / rehabilitación',
  'מתחיל לגמרי': 'Principiante total',
  'בסיסי': 'Básico',
  'בינוני': 'Intermedio',
  'מתקדם': 'Avanzado',
  'בבית': 'En casa',
  'בפארק / בחוץ': 'En el parque / al aire libre',
  'בחדר כושר': 'En el gimnasio',
  'צילום עסק / חנות': 'Fotografía de negocio / tienda',
  'צילום מוצרים': 'Fotografía de producto',
  'צילום אירוע (מסיבה / אירוע עסקי)': 'Fotografía de evento (fiesta / evento corporativo)',
  'צילום אישי / תדמית': 'Fotografía personal / imagen',
  'סרטון לרשתות (רילס / טיקטוק)': 'Video para redes sociales (Reels / TikTok)',
  'עריכת וידאו בלבד': 'Solo edición de video',
  'עריכת תמונות בלבד': 'Solo edición de fotos',
  'צילום נדל"ן / דירה': 'Fotografía inmobiliaria / apartamento',
  'עד שעה': 'Hasta una hora',
  'שעה-שעתיים': 'Una a dos horas',
  'חצי יום': 'Medio día',
  'יום מלא': 'Día completo',
  'צבע והתאמה': 'Color y ajuste',
  'הסרת רקע': 'Eliminación de fondo',
  'טקסט / כותרות': 'Texto / títulos',
  'מוזיקה': 'Música',
  'כתוביות': 'Subtítulos',
  'קיצור ומעברים': 'Cortes y transiciones',
  'מלצר / הגשה': 'Camarero / servicio',
  'ברמן': 'Barman',
  'שף / טבח': 'Chef / cocinero',
  'הפעלת ילדים / אנימציה': 'Animación infantil',
  'עזרה בהקמה / פירוק': 'Ayuda en montaje / desmontaje',
  'סדרן / אבטחה': 'Acomodador / seguridad',
  'DJ / מוזיקה': 'DJ / música',
  'צלם (ראה קטגוריה צילום)': 'Fotógrafo (ver categoría Fotografía)',
  'מסיבה פרטית': 'Fiesta privada',
  'אירוע עסקי': 'Evento corporativo',
  'חתונה / בר מצווה': 'Boda / Bar Mitzvah',
  'אירוע ילדים': 'Evento infantil',
  'יום הולדת': 'Cumpleaños',
  'עד 20': 'Hasta 20',
  '20–50': '20–50',
  '50–100': '50–100',
  '100–200': '100–200',
  'מעל 200': 'Más de 200',
  'עד 3 שעות': 'Hasta 3 horas',
  '5–8 שעות': '5–8 horas',
  'לחכות לטכנאי / שליח בבית': 'Esperar al técnico / mensajero en casa',
  'לעמוד בתור (עיריה, רופא, דואר)': 'Hacer fila (ayuntamiento, médico, correos)',
  'לאסוף / להחזיר ילד מגן / בית ספר': 'Recoger / llevar niño a guardería / escuela',
  'להעביר מפתח / מסמך': 'Entregar llave / documento',
  'להחזיר ציוד / פריט לחנות': 'Devolver equipo / artículo a la tienda',
  'לבדוק / לצלם דירה': 'Inspeccionar / fotografiar apartamento',
  'עזרה בטפסים / ביורוקרטיה': 'Ayuda con formularios / burocracia',
  'שליחות אישית': 'Recado personal',
  'טיפול ותחזוקה שוטפת': 'Cuidado y mantenimiento rutinario',
  'תיקון תקלה / אבחון': 'Reparación de avería / diagnóstico',
  'החלפת מצבר': 'Cambio de batería',
  'החלפת בלמים / רפידות': 'Cambio de frenos / pastillas',
  'החלפת שמן + פילטרים': 'Cambio de aceite + filtros',
  'החלפת צמיגים / גלגלים': 'Cambio de neumáticos / ruedas',
  'בדיקת מחשב (דיאגנוסטיקה)': 'Revisión por computadora (diagnóstico)',
  'טיפול מוסך מלא': 'Mantenimiento completo en taller',
  'הזנקה (פנצר / כבלים)': 'Asistencia de arranque (pinchazo / cables)',
  'שטיפת רכב / ניקוי': 'Lavado / limpieza de coche',
  'מזגן רכב': 'Aire acondicionado del coche',
  'הרכב לא מתניע': 'El coche no arranca',
  'רעשים מהמנוע': 'Ruidos del motor',
  'אור אזהרה דולק בלוח': 'Luz de advertencia encendida en el panel',
  'בלמים לא תקינים / רעש': 'Frenos defectuosos / ruido',
  'בעיית הילוכים': 'Problema de marchas',
  'דליפת נוזל / שמן': 'Fuga de líquido / aceite',
  'מזגן לא עובד': 'Aire acondicionado no funciona',
  'חשמל / אלקטרוניקה': 'Electricidad / electrónica',
  'אין תקלה — טיפול שוטף': 'No hay avería — mantenimiento rutinario',
  'טויוטה': 'Toyota',
  'מאזדה': 'Mazda',
  'הונדה': 'Honda',
  'יונדאי': 'Hyundai',
  'קיה': 'Kia',
  'סקודה': 'Skoda',
  'פולקסווגן': 'Volkswagen',
  'מרצדס': 'Mercedes',
  'אאודי': 'Audi',
  'רנו': 'Renault',
  'ניסאן': 'Nissan',
  'מיצובישי': 'Mitsubishi',
  'סובארו': 'Subaru',
  'וולבו': 'Volvo',
  'טסלה': 'Tesla',
  'פורד': 'Ford',
  'שברולט': 'Chevrolet',
  'בבית / ברחוב': 'En casa / en la calle',
  'במוסך': 'En el taller',
  'בצד הדרך (תקוע)': 'Al lado de la carretera (averiado)',
  'צריך גרירה למוסך': 'Necesita grúa al taller',
  'הטכנאי מגיע אליי': 'El técnico viene a mí',
  'אני מגיע למוסך': 'Voy al taller',
  'אחר': 'Otro',
  'Windows': 'Windows',
  'Mac / macOS': 'Mac / macOS',
  'Linux': 'Linux',
  'iOS / iPad': 'iOS / iPad',
  'Android': 'Android',
  'IKEA': 'IKEA',
  'KARE': 'KARE',
  'PayBox': 'PayBox',
  'BMW': 'BMW',
  'למשל: 3': 'Por ejemplo: 3',
  'למשל: 2': 'Por ejemplo: 2',
  'למשל: 50': 'Por ejemplo: 50',
  'למשל: 2018': 'Por ejemplo: 2018',
  'למשל: 20': 'Por ejemplo: 20',
  '0 = קרקע': '0 = Planta baja',
  'עיר, רחוב...': 'Ciudad, calle...',
  'עיר, רחוב, מספר...': 'Ciudad, calle, número...',
  'כתובת יעד...': 'Dirección de destino...',
  'למשל: סופר רמי לוי, רחוב הרצל...': 'Por ejemplo: Supermercado Rami Levy, calle Herzl...',
  'למשל: 200': 'Por ejemplo: 200',
  'חלב, לחם, עגבניות, ביצים...': 'Leche, pan, tomates, huevos...',
  'למשל: דוד כהן': 'Por ejemplo: David Cohen',
  'למשל: 050-1234567': 'Por ejemplo: 050-1234567',
  'למשל: ספה גדולה, 3 ארגזים, מקרר...': 'Por ejemplo: Sofá grande, 3 cajas, refrigerador...',
  'למשל: מקרר אמריקאי, 10 ארגזים...': 'Por ejemplo: Refrigerador americano, 10 cajas...',
  'למשל: מתמטיקה, אנגלית, פיזיקה...': 'Por ejemplo: Matemáticas, inglés, física...',
  'למשל: הכנה למבחן בגרות, צמצום פערים...': 'Por ejemplo: Preparación para selectividad, reducción de brechas...',
  'למשל: 1.5 שנים, 4, 7': 'Por ejemplo: 1.5 años, 4, 7',
  'למשל: לברדור, פודל, מעורב...': 'Por ejemplo: Labrador, caniche, mestizo...',
  'למשל: 2 פעמים ביום, תרופה בבוקר...': 'Por ejemplo: 2 veces al día, medicamento por la mañana...',
  'למשל: סכרת, אפילפסיה, אלרגיות...': 'Por ejemplo: Diabetes, epilepsia, alergias...',
  'למשל: אלרגיה לבוטנים, ילד עם אוטיזם, תרופות...': 'Por ejemplo: Alergia al maní, niño con autismo, medicamentos...',
  'למשל: כלב ידידותי, חתול...': 'Por ejemplo: Perro amigable, gato...',
  'למשל: רוסית, רומנית, ערבית...': 'Por ejemplo: Ruso, rumano, árabe...',
  'למשל: לרדת 5 קילו, להתכונן לריצת 10K...': 'Por ejemplo: Bajar 5 kilos, prepararme para carrera de 10K...',
  'למשל: בעיות גב, ברך פגועה, לחץ דם...': 'Por ejemplo: Problemas de espalda, rodilla lesionada, presión arterial...',
  'למשל: הרכב מתניע אבל משמיע רעש מוזר, נראה שהמצבר...': 'Por ejemplo: El coche arranca pero hace un ruido extraño, parece que la batería...',
  'למשל: עבודה אחת': 'Por ejemplo: Un trabajo',
};
export default es;
