// Auto-generated fil translations
const fil = {
  '🔧 אינסטלציה': '🔧 Tubero (Plumbing)',
  '⚡ חשמלאות': '⚡ Elektrisyan',
  '🌿 גינון': '🌿 Paghahalaman',
  '🧹 ניקיון': '🧹 Paglilinis',
  '🚛 הובלה': '🚛 Paglilipat (Moving)',
  '🎨 צביעה': '🎨 Pagpipinta',
  '🪵 נגרות': '🪵 Karpinterya',
  '❄️ מזגנים': '❄️ Mga Aircon',
  '🔐 מנעולן': '🔐 Locksmith',
  '🛒 קניות': '🛒 Pamimili',
  '📦 משלוח': '📦 Pagpapadala (Delivery)',
  '👶 בייביסיטר': '👶 Babysitter',
  '📚 שיעורים פרטיים': '📚 Mga Pribadong Tutor',
  '💻 מחשבים': '💻 Mga Computer',
  '🔨 הנדימן / תיקונים': '🔨 Handyman / Pagkukumpuni',
  '💪 עזרה פיזית': '💪 Tulong na Pisikal',
  '🏠 תחזוקת בית': '🏠 Pagpapanatili ng Bahay',
  '🚗 הסעות וטרמפים': '🚗 Pagsasakay at Ride-sharing',
  '🐶 בעלי חיים': '🐶 Mga Alagang Hayop',
  '👵 סיוע לקשישים': '👵 Tulong para sa mga Matatanda',
  '🏋️ כושר וספורט': '🏋️ Fitness at Sports',
  '📸 צילום ותוכן': '📸 Photography at Content',
  '🎉 אירועים': '🎉 Mga Kaganapan (Events)',
  '🤝 עזרה אישית': '🤝 Personal na Tulong',
  '🚗 רכב': '🚗 Sasakyan',
  '📋 אחר': '📋 Iba pa',
  'מה הבעיה? 🔧 (ניתן לבחור יותר מאחת)': 'Ano ang problema? 🔧 (Maaaring pumili ng higit sa isa)',
  'איפה בבית? (ניתן לבחור כמה)': 'Saan sa bahay? (Maaaring pumili ng ilan)',
  '🚨 יש זרימת מים פעילה עכשיו (נזק מתרחש)': '🚨 May aktibong pagtagas ng tubig ngayon (may nagaganap na pinsala)',
  'יודע איפה ברז המים הראשי': 'Alam kung nasaan ang main water valve',
  'מה צריך? ⚡ (ניתן לבחור יותר מאחת)': 'Ano ang kailangan? ⚡ (Maaaring pumili ng higit sa isa)',
  '🚨 אין חשמל עכשיו בכל הבית / בחלקו': '🚨 Walang kuryente ngayon sa buong bahay / sa ilang bahagi nito',
  'אילו חדרים מושפעים?': 'Aling mga silid ang apektado?',
  'לוח החשמל מעודכן ובעל היתר': 'Ang electrical panel ay updated at may permit',
  'מה צריך לעשות? 🌿 (ניתן לבחור יותר מאחת)': 'Ano ang kailangang gawin? 🌿 (Maaaring pumili ng higit sa isa)',
  'גודל הגינה': 'Sukat ng hardin',
  'איזה סוג גינה?': 'Anong uri ng hardin?',
  'צריך לפנות פסולת / ענפים': 'Kailangang mag-alis ng basura / mga sanga',
  'יש ציוד בבית (מקצרה, מסור, גזם...)': 'May gamit sa bahay (lawnmower, lagari, pruner...)',
  'חד-פעמי או טיפול שוטף?': 'Isang beses lang o tuluy-tuloy na pagpapanatili?',
  'איזה סוג ניקיון? 🧹 (ניתן לבחור יותר מאחת)': 'Anong uri ng paglilinis? 🧹 (Maaaring pumili ng higit sa isa)',
  'מה מנקים?': 'Ano ang nililinis?',
  'כמה חדרים? (לא כולל מטבח ושירותים)': 'Ilang silid? (hindi kasama ang kusina at banyo)',
  'כמה חדרי אמבטיה / שירותים?': 'Ilang banyo / palikuran?',
  'יש חומרי ניקוי בבית': 'May mga panlinis sa bahay',
  'יש ציוד (שואב אבק, מגב...)': 'May mga kagamitan (vacuum cleaner, mop...)',
  'חד-פעמי או קבוע?': 'Isang beses o regular?',
  'מתי להגיע? 📅': 'Kailan darating? 📅',
  'כתובת יעד — לאן מובילים? *': 'Address ng destinasyon — saan ililipat? *',
  'מה מובילים?': 'Ano ang ililipat?',
  'קומה במוצא': 'Palapag sa pinagmulan',
  'קומה ביעד': 'Palapag sa destinasyon',
  'יש מעלית במוצא': 'May elevator sa pinagmulan',
  'יש מעלית ביעד': 'May elevator sa destinasyon',
  'איזה רכב צריך?': 'Anong sasakyan ang kailangan?',
  'צריך עזרה באריזה': 'Kailangan ng tulong sa pag-iimpake',
  'צריך לפרק ולהרכיב רהיטים': 'Kailangang mag-disassemble at mag-assemble ng mga muwebles',
  'תיאור הפריטים (לא חובה)': 'Paglalarawan ng mga gamit (opsyonal)',
  'מה צריך לצבוע? (ניתן לבחור יותר מאחד)': 'Ano ang kailangang pinturahan? (Maaaring pumili ng higit sa isa)',
  'כמה חדרים / קירות?': 'Ilang silid / pader?',
  'שטח משוער (מ"ר)': 'Tinatayang lawak (sq.m.)',
  'יש צבע (לא צריך להביא)': 'May pintura (hindi na kailangang magdala)',
  'צריך הכנה — טיח / גבס / סתימת סדקים': 'Kailangan ng paghahanda — plaster / gypsum / pagtakip ng mga bitak',
  'מצב הקירות': 'Kondisyon ng mga pader',
  'איזה הכנה צריך?': 'Anong paghahanda ang kailangan?',
  'מה צריך? 🪵 (ניתן לבחור יותר מאחת)': 'Ano ang kailangan? 🪵 (Maaaring pumili ng higit sa isa)',
  'כמה פריטים?': 'Ilang gamit?',
  'מותג הריהוט (אם רלוונטי)': 'Brand ng muwebles (kung naaangkop)',
  'יש כלים בבית (מקדחה, פטיש...)': 'May mga kasangkapan sa bahay (drill, martilyo...)',
  'יש הוראות הרכבה / שרטוט': 'May mga instruksyon sa pag-assemble / diagram',
  'מה צריך? ❄️': 'Ano ang kailangan? ❄️',
  'כמה יחידות?': 'Ilang yunit?',
  'סוג מזגן': 'Uri ng aircon',
  'גיל המזגן': 'Edad ng aircon',
  'צריך הרכבה על הקיר (תליית יחידה פנימית)': 'Kailangan ng pagkakabit sa pader (pagbitin ng indoor unit)',
  'גישה ליחידה החיצונית': 'Access sa outdoor unit',
  'מה הבעיה? 🔐': 'Ano ang problema? 🔐',
  '🚨 ננעלתי בחוץ כרגע — זה דחוף מאוד': '🚨 Naka-lock ako sa labas ngayon — ito ay napaka-urgente',
  'סוג הדלת': 'Uri ng pinto',
  'סוג המנעול (אם ידוע)': 'Uri ng kandado (kung alam)',
  'מה קונים? 🛒 (ניתן לבחור יותר מאחד)': 'מה קונים? 🛒 (ניתן לבחור יותר מאחד)',
  'שם החנות / מיקום': 'Pangalan ng tindahan / lokasyon',
  'תקציב הקנייה (₪) משוער': 'Tinatayang budget sa pamimili (₪)',
  'רשימת קניות': 'Listahan ng bibilhin',
  'צריך להביא קבלה': 'Kailangang magdala ng resibo',
  'איך נשלם על הקנייה?': 'Paano babayaran ang pamimili?',
  'כתובת מסירה — לאן? *': 'Address ng paghahatid — saan? *',
  'מה מוסרים?': 'Ano ang ipapahatid?',
  'מתי צריך להגיע?': 'Kailan dapat dumating?',
  'שם המקבל (לא חובה)': 'Pangalan ng tatanggap (opsyonal)',
  'טלפון המקבל (לא חובה)': 'Numero ng tatanggap (opsyonal)',
  'שביר — יש לטפל בזהירות': 'Marupok — hawakan nang may pag-iingat',
  'צריך שמירה על קור (קירור)': 'Kailangan ng pagpapanatili ng lamig (refrigeration)',
  'כמה ילדים?': 'Ilang bata?',
  'גילאי הילדים': 'Mga edad ng mga bata',
  'מתי נדרשת הבייביסיטר? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang babysitter? 📅 (eksaktong petsa at oras)',
  'איפה?': 'Saan?',
  'מה נדרש לעשות? (ניתן לבחור כמה)': 'Ano ang kailangang gawin? (Maaaring pumili ng ilan)',
  'צרכים מיוחדים / אלרגיות / מידע חשוב': 'Mga espesyal na pangangailangan / alerdyi / mahalagang impormasyon',
  'יש חיות מחמד בבית': 'May mga alagang hayop sa bahay',
  'פרטי חיות המחמד': 'Mga detalye ng alagang hayop',
  'נדרש ניסיון בעזרה ראשונה / החייאה': 'Kailangan ng karanasan sa first aid / CPR',
  'מעשנים בבית': 'May naninigarilyo sa bahay',
  'איזה מקצוע? 📚': 'Anong asignatura? 📚',
  'כיתה / רמה': 'Antas / grado',
  'מתי נדרש השיעור? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang klase? 📅 (eksaktong petsa at oras)',
  'פרונטלי או אונליין?': 'Face-to-face o online?',
  'מטרה / תיאור (לא חובה)': 'Layunin / paglalarawan (opsyonal)',
  'יש לקות למידה / ADHD (נדרשת התאמה)': 'May learning disability / ADHD (kailangan ng adjustment)',
  'מה הבעיה? 💻 (ניתן לבחור יותר מאחת)': 'Ano ang problema? 💻 (Maaaring pumili ng higit sa isa)',
  'איזה מכשיר?': 'Anong device?',
  'מערכת הפעלה (אם ידוע)': 'Operating system (kung alam)',
  'איך מועדף?': 'Paano ang gusto?',
  '⚠️ יש נתונים חשובים שעלולים לאבד': '⚠️ May mahahalagang datos na maaaring mawala',
  'מה צריך לעשות? 🔨 (ניתן לבחור יותר מאחת)': 'Ano ang kailangang gawin? 🔨 (Maaaring pumili ng higit sa isa)',
  'סוג הקיר (אם רלוונטי)': 'Uri ng pader (kung naaangkop)',
  'כמה עבודות / פריטים?': 'Ilang trabaho / gamit?',
  'מה צריך? 💪': 'Ano ang kailangan? 💪',
  'מה מזיזים?': 'Ano ang ililipat?',
  'משקל משוער לפריט': 'Tinatayang bigat bawat gamit',
  'קומה (אם רלוונטי)': 'Palapag (kung naaangkop)',
  'כמה עוזרים צריך?': 'Ilang helper ang kailangan?',
  'מה צריך? 🏠 (ניתן לבחור יותר מאחת)': 'Ano ang kailangan? 🏠 (Maaaring pumili ng higit sa isa)',
  'גודל השטח / היקף העבודה': 'Sukat ng lugar / saklaw ng trabaho',
  'צריך לפנות / להשליך ציוד': 'Kailangang mag-alis / magtapon ng gamit',
  'מה מפנים?': 'Ano ang aalisin?',
  'איזה סוג נסיעה? 🚗': 'Anong uri ng biyahe? 🚗',
  'לאן נוסעים? *': 'Saan pupunta? *',
  'כמה נוסעים?': 'Ilang pasahero?',
  'יש כבודה גדולה / מזוודות': 'May malalaking bagahe / maleta',
  'כמה מזוודות?': 'Ilang maleta?',
  'צריך כיסא בטיחות לילד': 'Kailangan ng child safety seat',
  'כמה כיסאות בטיחות?': 'Ilang safety seat?',
  'מה צריך? 🐶': 'Ano ang kailangan? 🐶',
  'איזה חיה?': 'Anong hayop?',
  'גודל הכלב': 'Sukat ng aso',
  'גזע הכלב (אם ידוע)': 'Breed ng aso (kung alam)',
  'גיל הכלב': 'Edad ng aso',
  'אופי הכלב — ניתן לבחור כמה': 'Ugali ng aso — maaaring pumili ng ilan',
  'הכלב מסתדר עם כלבים אחרים?': 'Kasundo ba ng aso ang ibang mga aso?',
  'מחוסן ומעודכן': 'Bakunado at updated',
  'מסורס / מעוקר': 'Kapon (spayed/neutered)',
  'בית עם ילדים': 'Bahay na may mga bata',
  'בית עם חתולים': 'Bahay na may mga pusa',
  'חתול ביתי (לא יוצא החוצה)': 'Pusang bahay (hindi lumalabas)',
  'צריך החלפת חול / ניקוי ארגז': 'Kailangan ng pagpapalit ng buhangin / paglilinis ng litter box',
  'מתי נדרש השירות? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang serbisyo? 📅 (eksaktong petsa at oras)',
  'הוראות האכלה / תרופות': 'Mga instruksyon sa pagpapakain / gamot',
  'צרכים מיוחדים / מצב רפואי': 'Mga espesyal na pangangailangan / kondisyong medikal',
  'העובד יקבל מפתח לבית': 'Bibigyan ang trabahador ng susi ng bahay',
  'מה צריך? 👵 (ניתן לבחור יותר מאחת)': 'Ano ang kailangan? 👵 (Maaaring pumili ng higit sa isa)',
  'מתי נדרש הסיוע? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang tulong? 📅 (eksaktong petsa at oras)',
  'מצב הניידות של הקשיש': 'Kondisyon ng paggalaw ng matanda',
  'הקשיש צריך הסעה (יש רכב משלו או שצריך רכב של העובד)': 'Ang matanda ay kailangan ng transportasyon (may sariling sasakyan o kailangan ng sasakyan ng trabahador)',
  'לקשיש יש רכב משלו': 'Ang matanda ay may sariling sasakyan',
  'מצב קוגניטיבי (אם רלוונטי)': 'Kondisyong kognitibo (kung naaangkop)',
  'נדרש תזכורת / עזרה בנטילת תרופות': 'Kailangan ng paalala / tulong sa pag-inom ng gamot',
  'שפה מועדפת (אם רלוונטי)': 'Gustong wika (kung naaangkop)',
  'איזה אימון? 🏋️ (ניתן לבחור יותר מאחד)': 'Anong ehersisyo? 🏋️ (Maaaring pumili ng higit sa isa)',
  'רמת הכושר שלך': 'Antas ng iyong fitness',
  'מתי נדרש האימון? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang ehersisyo? 📅 (eksaktong petsa at oras)',
  'מטרה (לא חובה)': 'Layunin (opsyonal)',
  'מגבלות רפואיות / פציעות (לא חובה)': 'Mga limitasyong medikal / pinsala (opsyonal)',
  'יש ציוד בבית (משקולות, מזרון...)': 'May gamit sa bahay (dumbbells, yoga mat...)',
  'מה צריך? 📸 (ניתן לבחור יותר מאחד)': 'מה צריך? 📸 (ניתן לבחור יותר מאחד)',
  'כמה זמן?': 'Gaano katagal?',
  'צריך עריכה + תמונות/סרטונים מוגמרים': 'Kailangan ng editing + tapos na mga litrato/video',
  'איזה עריכה?': 'Anong uri ng editing?',
  'צריך צילום רחפן': 'Kailangan ng drone photography',
  'כמה תמונות / סרטונים סופיים צריך?': 'Ilang final na litrato / video ang kailangan?',
  'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)': 'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)',
  'סוג האירוע': 'Uri ng kaganapan',
  'כמה אורחים?': 'Ilang bisita?',
  'כמה שעות?': 'Ilang oras?',
  'נדרש מדים / תלבושת אחידה': 'Kailangan ng uniform',
  'מה צריך? 🤝 (ניתן לבחור יותר מאחד)': 'מה צריך? 🤝 (ניתן לבחור יותר מאחד)',
  'מתי נדרשת העזרה? 📅 (תאריך ושעות מדויקים)': 'Kailan kailangan ang tulong? 📅 (eksaktong petsa at oras)',
  'צריך רכב משל העובד': 'Kailangan ng sasakyan ng trabahador',
  'מערב ילדים (איסוף / הסעה)': 'Kasangkot ang mga bata (pagsundo / transportasyon)',
  'מה צריך? 🚗 (ניתן לבחור יותר מאחת)': 'Ano ang kailangan? 🚗 (Maaaring pumili ng higit sa isa)',
  'איזו תקלה? (אם יש)': 'Anong aberya? (kung mayroon)',
  'יצרן הרכב': 'Manufacturer ng sasakyan',
  'שנתון הרכב': 'Taon ng sasakyan',
  'איפה הרכב כעת?': 'Nasaan ang sasakyan ngayon?',
  '🚨 צריך גרירה / הובלת הרכב': '🚨 Kailangan ng tow / paghatak ng sasakyan',
  'יש חלקי חילוף (לא צריך להביא)': 'May mga spare parts (hindi na kailangang magdala)',
  'הערות נוספות (לא חובה)': 'Karagdagang komento (opsyonal)',
  'נזילה ממקור מסוים': 'Pagtagas mula sa partikular na pinagmulan',
  'סתימה בכיור / אמבטיה / שירותים': 'Baradong lababo / banyo / palikuran',
  'החלפת ברז': 'Pagpapalit ng gripo',
  'אסלה שלא מפסיקה לזרום': 'Inidoro na hindi humihinto ang agos',
  'דוד שמש / בוילר': 'Solar water heater / boiler',
  'התקנת מכשיר חדש (מדיח, מכונת כביסה)': 'Pagkakabit ng bagong appliance (dishwasher, washing machine)',
  'ריח / ביוב עולה': 'Amoy / umaapaw na dumi sa imburnal',
  'בדיקה כללית': 'Pangkalahatang inspeksyon',
  'מטבח': 'Kusina',
  'חדר אמבטיה': 'Banyo',
  'שירותים': 'Palikuran',
  'מרפסת': ' балкон (Balcony)',
  'מחוץ לבית': 'Sa labas ng bahay',
  'שקע / מפסק לא עובד': 'Hindi gumaganang outlet / switch',
  'נפילת חשמל (מפסק קפץ)': 'Power outage (tripped circuit breaker)',
  'התקנת שקע חדש': 'Pagkakabit ng bagong outlet',
  'החלפת נורה / גוף תאורה': 'Pagpapalit ng bumbilya / light fixture',
  'בדיקת לוח חשמל': 'Inspeksyon ng electrical panel',
  'חיווט לחדר / מקום חדש': 'Wiring para sa bagong silid / lugar',
  'התקנת מאוורר תקרה': 'Pagkakabit ng ceiling fan',
  'חיווט לדוד / למזגן': 'Wiring para sa water heater / aircon',
  'סלון': 'Sala',
  'חדר שינה': 'Silid-tulugan',
  'כל הבית': 'Buong bahay',
  'כיסוח דשא': 'Pagtabas ng damo',
  'גיזום עצים / שיחים': 'Pagputol ng mga puno / palumpong',
  'עישוב (ניכוש עשבים)': 'Pag-aalis ng mga damo',
  'ניקוי וסידור הגינה': 'Paglilinis at pag-aayos ng hardin',
  'פינוי ענפים / גזם': 'Pag-aalis ng mga sanga / pinutol na halaman',
  'שתילה / הקמת ערוגה': 'Pagtatanim / paggawa ng flower bed',
  'תכנון והקמת גינה חדשה': 'Pagpaplano at paggawa ng bagong hardin',
  'תיקון מערכת השקיה': 'Pagkukumpuni ng irrigation system',
  'קטנה — עד 20 מ"ר': 'Maliit — hanggang 20 sq.m.',
  'בינונית — 20–60 מ"ר': 'Katamtaman — 20–60 sq.m.',
  'גדולה — 60–150 מ"ר': 'Malaki — 60–150 sq.m.',
  'גדולה מאוד — מעל 150 מ"ר': 'Napakalaki — higit sa 150 sq.m.',
  'גינה פרטית בבית': 'Pribadong hardin sa bahay',
  'גינת בניין משותף': 'Hardin ng shared building',
  'מרפסת / גג': 'Balcony / rooftop',
  'שטח ציבורי / עסקי': 'Pampubliko / business area',
  'חד-פעמי': 'Isang beses lang',
  'שבועי': 'Lingguhan',
  'דו-שבועי': 'Bi-weekly',
  'חודשי': 'Buwanan',
  'ניקיון שוטף (שבועי / דו-שבועי)': 'Regular na paglilinis (lingguhan / bi-weekly)',
  'ניקוי עומק (אחת לחודש)': 'Deep cleaning (buwanan)',
  'ניקיון לפני / אחרי מעבר דירה': 'Paglilinis bago / pagkatapos lumipat ng bahay',
  'ניקיון לאחר שיפוץ': 'Paglilinis pagkatapos ng renovation',
  'ניקוי חלונות': 'Paglilinis ng bintana',
  'ניקוי שטיחים / ריפוד': 'Paglilinis ng carpet / upholstery',
  'ניקוי מטבח / תנור': 'Paglilinis ng kusina / oven',
  'ניקוי משרד / עסק': 'Paglilinis ng opisina / negosyo',
  'דירה': 'Apartment',
  'בית פרטי': 'Pribadong bahay',
  'משרד': 'Opisina',
  'מחסן / חדר': 'Warehouse / silid',
  'מעבר דירה מלא': 'Full house move',
  'כמה פריטים / ארגזים': 'Ilang gamit / kahon',
  'רהיט בודד (ספה, מיטה, ארון)': 'Isang pirasong muwebles (sofa, kama, cabinet)',
  'ציוד / מכשיר גדול': 'Malaking kagamitan / appliance',
  'טנדר / סטיישן מספיק': 'Sapat na ang van / station wagon',
  'ואן בינוני': 'Katamtamang van',
  'משאית קטנה': 'Maliit na trak',
  'משאית גדולה': 'Malaking trak',
  'לא בטוח': 'Hindi sigurado',
  'קירות פנים (חדר / דירה)': 'Mga pader sa loob (silid / apartment)',
  'תקרה': 'Kisame',
  'קירות חוץ': 'Mga panlabas na pader',
  'גדר / קיר חיצוני': 'Bakod / panlabas na pader',
  'דלת / חלון': 'Pinto / bintana',
  'ריהוט עץ': 'Muwebles na kahoy',
  'מדרגות': 'Mga hagdan',
  'חדש — רק צבע': 'Bago — pintura lang',
  'תקין — צריך שכבה': 'Maayos — kailangan ng bagong layer',
  'דורש תיקון קל': 'Kailangan ng kaunting pagkumpuni',
  'דורש שיפוץ מקדים': 'Kailangan ng pre-renovation',
  'טיח / מריחת גבס': 'Plaster / paglalagay ng gypsum',
  'סתימת סדקים': 'Pagtakip ng mga bitak',
  'הסרת טפט ישן': 'Pag-aalis ng lumang wallpaper',
  'שיוף קיר ישן': 'Pag-sanding ng lumang pader',
  'תיקון רטיבות': 'Pagkumpuni ng tagas/moisture',
  'תיקון / חיזוק רהיט שבור': 'Pagkumpuni / pagpapatibay ng sirang muwebles',
  'בניית מדף / ארון מותאם': 'Paggawa ng shelf / cabinet na custom',
  'החלפת / תיקון דלת': 'Pagpapalit / pagkumpuni ng pinto',
  'התקנת מטבח / ארונות': 'Pagkakabit ng kusina / mga cabinet',
  'עבודת עץ מותאמת אישית': 'Custom na gawang kahoy',
  'פירוק רהיטים': 'Pag-disassemble ng mga muwebles',
  'פריט אחד': 'Isang gamit',
  '2–3 פריטים': '2-3 gamit',
  '4–6 פריטים': '4-6 gamit',
  'יותר מ-6': 'Higit sa 6',
  'הום סנטר': 'Home Center',
  'אייס': 'ACE',
  'לא רלוונטי': 'Hindi naaangkop',
  'התקנת מזגן חדש': 'Pagkakabit ng bagong aircon',
  'פירוק מזגן': 'Pag-aalis ng aircon',
  'ניקוי / שירות שנתי': 'Paglilinis / taunang serbisyo',
  'מזגן לא מקרר / לא מחמם': 'Hindi lumalamig / hindi uminit ang aircon',
  'מזגן מטפטף מים': 'Tumutulo ang tubig sa aircon',
  'מזגן לא נדלק': 'Hindi bumubukas ang aircon',
  'רעש / רטיט במזגן': 'Ingay / pagyanig sa aircon',
  'מפוצל (split)': 'Split type',
  'נייד': 'Portable',
  'מיני מרכזי': 'Mini-central',
  'מרכזי / תעלות': 'Central / duct',
  'לא יודע': 'Hindi ko alam',
  'חדש (עד שנתיים)': 'Bago (hanggang 2 taon)',
  'מעל 7 שנים': 'Higit sa 7 taon',
  'מרפסת / גג נגיש': 'Balcony / accessible rooftop',
  'צריך סולם': 'Kailangan ng hagdan',
  'צריך בניין / סנפלינג': 'Kailangan ng building access / rappelling',
  '🚨 ננעלתי בחוץ — פריצת מנעול': '🚨 Naka-lock ako sa labas — pag-pick ng lock',
  'החלפת מנעול': 'Pagpapalit ng kandado',
  'התקנת מנעול חדש / חיזוק': 'Pagkakabit ng bagong kandado / pagpapatibay',
  'שכפול מפתח': 'Pagkopya ng susi',
  'תיקון / ידית דלת': 'Pagkumpuni / hawakan ng pinto',
  'כספת — פתיחה / התקנה': 'Vault — pagbukas / pagkakabit',
  'צילינדר חסום / מפתח שבור בפנים': 'Baradong cylinder / sirang susi sa loob',
  'דלת דירה': 'Pinto ng apartment',
  'דלת בית פרטי': 'Pinto ng pribadong bahay',
  'דלת מחסן / חניה': 'Pinto ng warehouse / garahe',
  'דלת משרד': 'Pinto ng opisina',
  'מכונית': 'Kotse',
  'צילינדר רגיל': 'Standard na cylinder',
  'מולטילוק': 'Mul-T-Lock',
  'מנעול חכם / קוד': 'Smart lock / code lock',
  'בריח': 'Deadbolt',
  'מזון (סופר / מכולת)': 'Pagkain (supermarket / grocery)',
  'תרופות / בית מרקחת': 'Gamot / botika',
  'פירות וירקות (שוק)': 'Prutas at gulay (palengke)',
  'ציוד / חנות ספציפית': 'Gamit / espesyal na tindahan',
  'אלכוהול': 'Alak',
  'קניות כלליות — יסופק רשימה': 'Pangkalahatang pamimili — magbibigay ng listahan',
  'מזומן בחזרה': 'Cash back',
  'העברה בביט': 'Paglipat sa Bit',
  'אשראי': 'Credit card',
  'מסמכים / מעטפה': 'Mga dokumento / sobre',
  'חבילה קטנה (כמו נעליים)': 'Maliit na pakete (tulad ng sapatos)',
  'חבילה בינונית (כמו מזוודה)': 'Katamtamang pakete (tulad ng maleta)',
  'חבילה גדולה / כבדה': 'Malaki / mabigat na pakete',
  'אוכל / מזון': 'Pagkain',
  'תרופות': 'Gamot',
  '🔴 מיידי — תוך שעה': '🔴 Agaran — loob ng isang oras',
  'היום עד שעה מסוימת': 'Ngayon hanggang sa partikular na oras',
  'היום — גמיש': 'Ngayon — flexible',
  'מחר': 'Bukas',
  'גמיש לחלוטין': 'Lubos na flexible',
  'בבית שלנו': 'Sa bahay namin',
  'בבית הבייביסיטר': 'Sa bahay ng babysitter',
  'גמיש': 'Flexible',
  'שמירה בלבד': 'Pagbabantay lang',
  'הכנת ארוחה': 'Paghahanda ng pagkain',
  'השכבה לשינה': 'Pagpapatulog',
  'עזרה בשיעורים': 'Tulong sa takdang-aralin',
  'אמבטיה': 'Paliligo',
  'הסעה / איסוף מגן': 'Pagsundo / transportasyon mula sa daycare',
  'משחק ופעילות': 'Paglalaro at aktibidad',
  'כיתה א-ו (יסודי)': 'Grado 1-6 (elementary)',
  'כיתה ז-ט (חטיבה)': 'Grado 7-9 (junior high)',
  'כיתה י-יב (תיכון)': 'Grado 10-12 (senior high)',
  'הכנה לבגרות': 'Paghahanda sa pagsusulit',
  'אקדמיה / אוניברסיטה': 'Akademya / unibersidad',
  'מבוגר': 'Matanda',
  'פרונטלי — בבית': 'Face-to-face — sa bahay',
  'פרונטלי — אצל המורה': 'Face-to-face — sa guro',
  'זום / אונליין': 'Zoom / online',
  'מחשב איטי מאוד': 'Napakabagal na computer',
  'מחשב לא נדלק': 'Hindi bumubukas ang computer',
  'וירוס / תוכנה זדונית': 'Virus / malware',
  'בעיית אינטרנט / WiFi': 'Problema sa internet / WiFi',
  'התקנת תוכנה / Windows': 'Pagkakabit ng software / Windows',
  'גיבוי נתונים / שחזור': 'Data backup / recovery',
  'בעיית מסך / מקלדת / עכבר': 'Problema sa screen / keyboard / mouse',
  'הגדרת אימייל / חשבון': 'Email / account setup',
  'התקנת מדפסת': 'Pagkakabit ng printer',
  'מחשב נייח': 'Desktop computer',
  'לפטופ (נייד)': 'Laptop',
  'טאבלט': 'Tablet',
  'סמארטפון': 'Smartphone',
  'ראוטר / רשת': 'Router / network',
  'מדפסת': 'Printer',
  'כמה מכשירים': 'Ilang device',
  'ביקור בית / עסק': 'Pagbisita sa bahay / negosyo',
  'מרחוק (remote)': 'Remote',
  'תליית טלוויזיה על קיר': 'Pagbitin ng TV sa pader',
  'תליית מדף / תמונה': 'Pagbitin ng shelf / larawan',
  'התקנת וילון / בלינד': 'Pagkakabit ng kurtina / blind',
  'החלפת ידית / מנגנון': 'Pagpapalit ng hawakan / mekanismo',
  'תיקון ריהוט שבור': 'Pagkumpuni ng sirang muwebles',
  'הרכבת ריהוט מקופסה': 'Pag-assemble ng muwebles mula sa kahon',
  'איטום / גבס קטן': 'Sealing / maliit na gawaing gypsum',
  'התקנת מנורה / גוף תאורה': 'Pagkakabit ng bumbilya / light fixture',
  'תיקון דלת / ציר': 'Pagkumpuni ng pinto / hinge',
  'בטון / בלוק': 'Kongkreto / block',
  'גבס': 'Gypsum',
  'עבודה אחת': 'Isang trabaho',
  '2–3 עבודות': '2-3 trabaho',
  '4 ומעלה': '4 o higit pa',
  'להעלות / להוריד פריט כבד': 'Pagbubuhat ng mabigat na gamit',
  'לסחוב ארגזים / קרטונים': 'Pagbubuhat ng mga kahon / karton',
  'פריקת משאית / ואן': 'Pag-unload ng trak / van',
  'עזרה בהזזת ריהוט בתוך הבית': 'Tulong sa paglipat ng muwebles sa loob ng bahay',
  'עזרה במעבר דירה (ללא נהג)': 'Tulong sa paglipat ng bahay (walang driver)',
  'טעינת פריטים לרכב': 'Pagkakarga ng mga gamit sa sasakyan',
  'עד 15 ק"ג': 'Hanggang 15 kg',
  '15–30 ק"ג': '15-30 kg',
  '30–60 ק"ג': '30-60 kg',
  'מעל 60 ק"ג': 'Higit sa 60 kg',
  'ארגזים רבים': 'Maraming kahon',
  'קרקע': 'Ground floor',
  'קומה 1': 'Unang palapag',
  'קומה 2': 'Ikalawang palapag',
  'קומה 3+': 'Ikatlong palapag pataas',
  'יש מעלית': 'May elevator',
  'אחד מספיק': 'Sapat na ang isa',
  'שניים': 'Dalawa',
  'שלושה ומעלה': 'Tatlo o higit pa',
  'ניקוי / פינוי מחסן': 'Paglilinis / pag-aalis ng warehouse',
  'סידור וארגון מחסן': 'Pag-aayos at organisasyon ng warehouse',
  'ניקוי מרזבים / גג': 'Paglilinis ng gutter / rooftop',
  'פינוי פסולת / ריהוט ישן': 'Pag-aalis ng basura / lumang muwebles',
  'ניקוי מרפסת / חצר': 'Paglilinis ng balcony / bakuran',
  'ארגון בית כללי': 'Pangkalahatang pag-aayos ng bahay',
  'תיקונים קטנים בבית': 'Maliliit na pagkumpuni sa bahay',
  'קטן — עד שעה': 'Maliit — hanggang isang oras',
  'בינוני — 2–3 שעות': 'Katamtaman — 2-3 oras',
  'גדול — חצי יום': 'Malaki — kalahating araw',
  'גדול מאוד — יום שלם': 'Napakalaki — buong araw',
  'ריהוט ישן': 'Lumang muwebles',
  'פסולת בניין': 'Basura sa konstruksyon',
  'קרטונים': 'Mga karton',
  'גזם / ענפים': 'Mga pinutol na halaman / sanga',
  'ציוד חשמלי': 'Gamit na elektrikal',
  'אשפה כללית': 'Pangkalahatang basura',
  'נסיעה לשדה התעופה / ממנו': 'Biyahe papunta / galing sa airport',
  'הסעה לאירוע': 'Transportasyon sa kaganapan',
  'הסעת ילדים (גן / בית ספר / חוגים)': 'Paghatid sa mga bata (daycare / paaralan / extracurricular)',
  'טרמפ לעבודה / עיר אחרת': 'Sakay papunta sa trabaho / ibang lungsod',
  'נהג פרטי לכמה שעות': 'Private driver para sa ilang oras',
  'נסיעה לבית חולים / קופת חולים': 'Biyahe sa ospital / klinika',
  'הסעת קשיש': 'Transportasyon para sa matanda',
  '1': '1',
  '1–2': '1-2',
  'טיול עם הכלב': 'Paglalakad kasama ang aso',
  'שמירה / פנסיון בבית המטפל': 'Pagbabantay / boarding sa bahay ng caregiver',
  'ביקור יומי (האכלה / השקיה / טיול קצר)': 'Araw-araw na pagbisita (pagpapakain / pagdidilig / maikling lakad)',
  'הסעה לוטרינר / טיפוח': 'Transportasyon sa beterinaryo / grooming',
  'אילוף / אימון': 'Pagsasanay / training',
  'טיפוח / גזיזה / אמבטיה': 'Grooming / paggupit / paliligo',
  'כלב': 'Aso',
  'חתול': 'Pusa',
  'ארנב / מכרסם': 'Kuneho / rodent',
  'ציפור': 'Ibon',
  'זוחל': 'Reptile',
  'דגים': 'Isda',
  'כמה חיות': 'Ilang hayop',
  'קטן — עד 10 ק"ג': 'Maliit — hanggang 10 kg',
  'בינוני — 10–25 ק"ג': 'Katamtaman — 10-25 kg',
  'גדול — 25–45 ק"ג': 'Malaki — 25-45 kg',
  'ענק — מעל 45 ק"ג': 'Napakalaki — higit sa 45 kg',
  'גור (עד שנה)': 'Puppy (hanggang isang taon)',
  'צעיר (1–3 שנים)': 'Bata (1-3 taon)',
  'בוגר (3–7 שנים)': 'Adult (3-7 taon)',
  'מבוגר (מעל 7)': 'Matanda (higit sa 7)',
  'ידידותי': 'Friendly',
  'רגוע': 'Kalmado',
  'אנרגטי': 'Energetic',
  'חרדתי': 'Anxious',
  'תקיף / תוקפני': 'Agresibo',
  'מושך ברצועה': 'Humihila sa tali',
  'בורח לפעמים': 'Minsan tumatakas',
  'כן, ידידותי': 'Oo, friendly',
  'בסדר עם היכרות': 'Okay pagkatapos magkakilala',
  'מסתייג': 'Nag-aalinlangan',
  'ליווי לרופא / קופת חולים': 'Pag-assist sa doktor / klinika',
  'ליווי לבית מרקחת / קניות': 'Pag-assist sa botika / pamimili',
  'קניות עבור הקשיש': 'Pamimili para sa matanda',
  'עזרה בבית (כביסה, ניקיון קל)': 'Tulong sa bahay (paglalaba, magaan na paglilinis)',
  'חברה וביקור (שיחה, הליכה)': 'Pakikipag-usap at pagbisita (pag-uusap, paglakad)',
  'עזרה בטכנולוגיה (טלפון, מחשב)': 'Tulong sa teknolohiya (telepono, computer)',
  'עזרה בטפסים / ביורוקרטיה': 'Tulong sa mga form / burukrasya',
  'הכנת ארוחה': 'Paghahanda ng pagkain',
  'הולך באופן עצמאי': 'Nakakapaglakad nang mag-isa',
  'זקוק לעזרה בהליכה / תמיכה': 'Kailangan ng tulong sa paglakad / suporta',
  'מרותק לכיסא גלגלים': 'Naka-wheelchair',
  'מרותק למיטה': 'Nakaratay sa kama',
  'צלול ועצמאי': 'Malinaw ang isip at independent',
  'זיכרון ירוד קל': 'Bahagyang mahinang memorya',
  'דמנציה / אלצהיימר': 'Dementia / Alzheimer\'s',
  'אימון כושר כללי': 'Pangkalahatang fitness training',
  'ריצה / הכנה לריצה': 'Pagtakbo / paghahanda sa pagtakbo',
  'יוגה': 'Yoga',
  'פילאטיס': 'Pilates',
  'אימון כוח / הרמת משקולות': 'Strength training / weightlifting',
  'אימון בית (ללא ציוד)': 'Home workout (walang gamit)',
  'אימון בחדר כושר': 'Workout sa gym',
  'שחייה': 'Paglangoy',
  'אימון תפקודי / שיקום': 'Functional training / rehabilitation',
  'מתחיל לגמרי': 'Beginner',
  'בסיסי': 'Basic',
  'בינוני': 'Intermediate',
  'מתקדם': 'Advanced',
  'בבית': 'Sa bahay',
  'בפארק / בחוץ': 'Sa parke / sa labas',
  'בחדר כושר': 'Sa gym',
  'צילום עסק / חנות': 'Photography ng negosyo / tindahan',
  'צילום מוצרים': 'Product photography',
  'צילום אירוע (מסיבה / אירוע עסקי)': 'Photography ng kaganapan (party / business event)',
  'צילום אישי / תדמית': 'Personal photography / portrait',
  'סרטון לרשתות (רילס / טיקטוק)': 'Video para sa social media (Reels / TikTok)',
  'עריכת וידאו בלבד': 'Video editing lang',
  'עריכת תמונות בלבד': 'Photo editing lang',
  'צילום נדל"ן / דירה': 'Photography ng real estate / apartment',
  'עד שעה': 'Hanggang isang oras',
  'שעה-שעתיים': 'Isang oras-dalawang oras',
  'חצי יום': 'Kalahating araw',
  'יום מלא': 'Buong araw',
  'צבע והתאמה': 'Kulay at adjustment',
  'הסרת רקע': 'Pag-aalis ng background',
  'טקסט / כותרות': 'Text / mga pamagat',
  'מוזיקה': 'Musika',
  'כתוביות': 'Mga subtitle',
  'קיצור ומעברים': 'Pagpapaikli at mga transition',
  'מלצר / הגשה': 'Waiter / serving',
  'ברמן': 'Bartender',
  'שף / טבח': 'Chef / cook',
  'הפעלת ילדים / אנימציה': 'Children\'s entertainment / animation',
  'עזרה בהקמה / פירוק': 'Tulong sa set-up / pack-up',
  'סדרן / אבטחה': 'Usher / security',
  'DJ / מוזיקה': 'DJ / musika',
  'צלם (ראה קטגוריה צילום)': 'Photographer (tingnan ang kategoryang photography)',
  'מסיבה פרטית': 'Pribadong party',
  'אירוע עסקי': 'Business event',
  'חתונה / בר מצווה': 'Kasal / Bar Mitzvah',
  'אירוע ילדים': 'Kaganapan para sa mga bata',
  'יום הולדת': 'Kaarawan',
  'עד 20': 'Hanggang 20',
  '20–50': '20-50',
  '50–100': '50-100',
  '100–200': '100-200',
  'מעל 200': 'Higit sa 200',
  'עד 3 שעות': 'Hanggang 3 oras',
  '5–8 שעות': '5-8 oras',
  'לחכות לטכנאי / שליח בבית': 'Paghihintay sa technician / courier sa bahay',
  'לעמוד בתור (עיריה, רופא, דואר)': 'Pumila (munisipyo, doktor, post office)',
  'לאסוף / להחזיר ילד מגן / בית ספר': 'Pagsundo / paghatid sa bata sa daycare / paaralan',
  'להעביר מפתח / מסמך': 'Pag-abot ng susi / dokumento',
  'להחזיר ציוד / פריט לחנות': 'Pagbalik ng gamit sa tindahan',
  'לבדוק / לצלם דירה': 'Pag-inspeksyon / pag-litrato ng apartment',
  'עזרה בטפסים / ביורוקרטיה': 'Tulong sa mga form / burukrasya',
  'שליחות אישית': 'Personal na courier',
  'טיפול ותחזוקה שוטפת': 'Regular na maintenance',
  'תיקון תקלה / אבחון': 'Pagkumpuni ng aberya / diagnosis',
  'החלפת מצבר': 'Pagpapalit ng baterya',
  'החלפת בלמים / רפידות': 'Pagpapalit ng brakes / brake pads',
  'החלפת שמן + פילטרים': 'Pagpapalit ng langis + filters',
  'החלפת צמיגים / גלגלים': 'Pagpapalit ng gulong',
  'בדיקת מחשב (דיאגנוסטיקה)': 'Computer diagnosis',
  'טיפול מוסך מלא': 'Full car service',
  'הזנקה (פנצר / כבלים)': 'Jumpstart (flat tire / cables)',
  'שטיפת רכב / ניקוי': 'Paghuhugas / paglilinis ng kotse',
  'מזגן רכב': 'Aircon ng kotse',
  'הרכב לא מתניע': 'Hindi bumubukas ang kotse',
  'רעשים מהמנוע': 'רעשים מהמנוע',
  'אור אזהרה דולק בלוח': 'Naka-on ang warning light sa dashboard',
  'בלמים לא תקינים / רעש': 'Hindi maayos na preno / ingay',
  'בעיית הילוכים': 'Problema sa transmission',
  'דליפת נוזל / שמן': 'Pagtagas ng likido / langis',
  'מזגן לא עובד': 'Hindi gumagana ang aircon',
  'חשמל / אלקטרוניקה': 'Kuryente / electronics',
  'אין תקלה — טיפול שוטף': 'Walang aberya — regular na maintenance',
  'טויוטה': 'Toyota',
  'מאזדה': 'Mazda',
  'הונדה': 'Honda',
  'יונדאי': 'Hyundai',
  'קיה': 'Kia',
  'סקודה': 'Skoda',
  'פולקסווגן': 'Volkswagen',
  'מרצדס': 'Mercedes',
  'אאודי': 'Audi',
  'רנו': 'Renault',
  'ניסאן': 'Nissan',
  'מיצובישי': 'Mitsubishi',
  'סובארו': 'Subaru',
  'וולבו': 'Volvo',
  'טסלה': 'Tesla',
  'פורד': 'Ford',
  'שברולט': 'Chevrolet',
  'בבית / ברחוב': 'Sa bahay / sa kalye',
  'במוסך': 'Sa talyer (garage)',
  'בצד הדרך (תקוע)': 'Sa tabi ng kalsada (na-stranded)',
  'צריך גרירה למוסך': 'Kailangan ng tow sa talyer',
  'הטכנאי מגיע אליי': 'Ang technician ang pupunta sa akin',
  'אני מגיע למוסך': 'Ako ang pupunta sa talyer',
  'אחר': 'Iba pa',
  'Windows': 'Windows',
  'Mac / macOS': 'Mac / macOS',
  'Linux': 'Linux',
  'iOS / iPad': 'iOS / iPad',
  'Android': 'Android',
  'IKEA': 'IKEA',
  'KARE': 'KARE',
  'PayBox': 'PayBox',
  'BMW': 'BMW',
  'למשל: 3': 'Halimbawa: 3',
  'למשל: 2': 'Halimbawa: 2',
  'למשל: 50': 'Halimbawa: 50',
  'למשל: 2018': 'Halimbawa: 2018',
  'למשל: 20': 'Halimbawa: 20',
  '0 = קרקע': '0 = ground floor',
  'עיר, רחוב...': 'Lungsod, kalye...',
  'עיר, רחוב, מספר...': 'Lungsod, kalye, numero...',
  'כתובת יעד...': 'Address ng destinasyon...',
  'למשל: סופר רמי לוי, רחוב הרצל...': 'Halimbawa: Supermarket Rami Levy, kalye Herzl...',
  'למשל: 200': 'Halimbawa: 200',
  'חלב, לחם, עגבניות, ביצים...': 'Gatas, tinapay, kamatis, itlog...',
  'למשל: דוד כהן': 'Halimbawa: David Cohen',
  'למשל: 050-1234567': 'Halimbawa: 050-1234567',
  'למשל: ספה גדולה, 3 ארגזים, מקרר...': 'Halimbawa: Malaking sofa, 3 kahon, refrigerator...',
  'למשל: מקרר אמריקאי, 10 ארגזים...': 'Halimbawa: American-style refrigerator, 10 kahon...',
  'למשל: מתמטיקה, אנגלית, פיזיקה...': 'Halimbawa: Matematika, Ingles, Pisika...',
  'למשל: הכנה למבחן בגרות, צמצום פערים...': 'Halimbawa: Paghahanda sa pagsusulit, pag-fill ng gaps...',
  'למשל: 1.5 שנים, 4, 7': 'Halimbawa: 1.5 taon, 4, 7',
  'למשל: לברדור, פודל, מעורב...': 'Halimbawa: Labrador, Poodle, mixed breed...',
  'למשל: 2 פעמים ביום, תרופה בבוקר...': 'Halimbawa: 2 beses sa isang araw, gamot sa umaga...',
  'למשל: סכרת, אפילפסיה, אלרגיות...': 'Halimbawa: Diabetes, epilepsy, mga alerdyi...',
  'למשל: אלרגיה לבוטנים, ילד עם אוטיזם, תרופות...': 'Halimbawa: Peanut allergy, batang may autism, mga gamot...',
  'למשל: כלב ידידותי, חתול...': 'Halimbawa: Friendly na aso, pusa...',
  'למשל: רוסית, רומנית, ערבית...': 'Halimbawa: Ruso, Romanian, Arabo...',
  'למשל: לרדת 5 קילו, להתכונן לריצת 10K...': 'Halimbawa: Magbawas ng 5 kilo, maghanda para sa 10K na takbo...',
  'למשל: בעיות גב, ברך פגועה, לחץ דם...': 'Halimbawa: Sakit sa likod, pinsala sa tuhod, presyon ng dugo...',
  'למשל: הרכב מתניע אבל משמיע רעש מוזר, נראה שהמצבר...': 'Halimbawa: Nag-start ang kotse pero may kakaibang ingay, mukhang ang baterya...',
  'למשל: עבודה אחת': 'Halimbawa: Isang trabaho',
};
export default fil;
