// Auto-generated fr translations
const fr = {
  '🔧 אינסטלציה': '🔧 Plomberie',
  '⚡ חשמלאות': '⚡ Électricité',
  '🌿 גינון': '🌿 Jardinage',
  '🧹 ניקיון': '🧹 Nettoyage',
  '🚛 הובלה': '🚛 Déménagement',
  '🎨 צביעה': '🎨 Peinture',
  '🪵 נגרות': '🪵 Menuiserie',
  '❄️ מזגנים': '❄️ Climatisation',
  '🔐 מנעולן': '🔐 Serrurerie',
  '🛒 קניות': '🛒 Courses',
  '📦 משלוח': '📦 Livraison',
  '👶 בייביסיטר': '👶 Baby-sitting',
  '📚 שיעורים פרטיים': '📚 Cours particuliers',
  '💻 מחשבים': '💻 Informatique',
  '🔨 הנדימן / תיקונים': '🔨 Homme à tout faire / Réparations',
  '💪 עזרה פיזית': '💪 Aide physique',
  '🏠 תחזוקת בית': '🏠 Entretien de la maison',
  '🚗 הסעות וטרמפים': '🚗 Transports et covoiturage',
  '🐶 בעלי חיים': '🐶 Animaux',
  '👵 סיוע לקשישים': '👵 Aide aux personnes âgées',
  '🏋️ כושר וספורט': '🏋️ Fitness et sport',
  '📸 צילום ותוכן': '📸 Photographie et contenu',
  '🎉 אירועים': '🎉 Événements',
  '🤝 עזרה אישית': '🤝 Aide personnelle',
  '🚗 רכב': '🚗 Véhicule',
  '📋 אחר': '📋 Autre',
  'מה הבעיה? 🔧 (ניתן לבחור יותר מאחת)': 'Quel est le problème ? 🔧 (plusieurs choix possibles)',
  'איפה בבית? (ניתן לבחור כמה)': 'Où dans la maison ? (plusieurs choix possibles)',
  '🚨 יש זרימת מים פעילה עכשיו (נזק מתרחש)': '🚨 Il y a une fuite d\'eau active en ce moment (dégâts en cours)',
  'יודע איפה ברז המים הראשי': 'Je sais où se trouve le robinet d\'arrêt principal',
  'מה צריך? ⚡ (ניתן לבחור יותר מאחת)': 'De quoi avez-vous besoin ? ⚡ (plusieurs choix possibles)',
  '🚨 אין חשמל עכשיו בכל הבית / בחלקו': '🚨 Il n\'y a plus d\'électricité dans toute la maison ou une partie',
  'אילו חדרים מושפעים?': 'Quelles pièces sont touchées ?',
  'לוח החשמל מעודכן ובעל היתר': 'Le tableau électrique est aux normes',
  'מה צריך לעשות? 🌿 (ניתן לבחור יותר מאחת)': 'Que faut-il faire ? 🌿 (plusieurs choix possibles)',
  'גודל הגינה': 'Taille du jardin',
  'איזה סוג גינה?': 'Quel type de jardin ?',
  'צריך לפנות פסולת / ענפים': 'Besoin d\'évacuer des déchets / branches',
  'יש ציוד בבית (מקצרה, מסור, גזם...)': 'Il y a du matériel à la maison (tondeuse, scie, taille-haie...)',
  'חד-פעמי או טיפול שוטף?': 'Prestation unique ou entretien régulier ?',
  'איזה סוג ניקיון? 🧹 (ניתן לבחור יותר מאחת)': 'Quel type de nettoyage ? 🧹 (plusieurs choix possibles)',
  'מה מנקים?': 'Que faut-il nettoyer ?',
  'כמה חדרים? (לא כולל מטבח ושירותים)': 'Combien de pièces ? (hors cuisine et toilettes)',
  'כמה חדרי אמבטיה / שירותים?': 'Combien de salles de bain / toilettes ?',
  'יש חומרי ניקוי בבית': 'Il y a des produits de nettoyage à la maison',
  'יש ציוד (שואב אבק, מגב...)': 'Il y a du matériel (aspirateur, serpillère...)',
  'חד-פעמי או קבוע?': 'Unique ou régulier ?',
  'מתי להגיע? 📅': 'Quand intervenir ? 📅',
  'כתובת יעד — לאן מובילים? *': 'Adresse de destination — Où transporter ? *',
  'מה מובילים?': 'Que faut-il transporter ?',
  'קומה במוצא': 'Étage de départ',
  'קומה ביעד': 'Étage d\'arrivée',
  'יש מעלית במוצא': 'Il y a un ascenseur au départ',
  'יש מעלית ביעד': 'Il y a un ascenseur à l\'arrivée',
  'איזה רכב צריך?': 'Quel véhicule est nécessaire ?',
  'צריך עזרה באריזה': 'Besoin d\'aide pour l\'emballage',
  'צריך לפרק ולהרכיב רהיטים': 'Besoin de démonter et remonter des meubles',
  'תיאור הפריטים (לא חובה)': 'Description des objets (facultatif)',
  'מה צריך לצבוע? (ניתן לבחור יותר מאחד)': 'Que faut-il peindre ? (plusieurs choix possibles)',
  'כמה חדרים / קירות?': 'Nombre de pièces / murs ?',
  'שטח משוער (מ"ר)': 'Surface estimée (m²)',
  'יש צבע (לא צריך להביא)': 'J\'ai la peinture (pas besoin d\'en apporter)',
  'צריך הכנה — טיח / גבס / סתימת סדקים': 'Besoin de préparation — enduit / plâtre / rebouchage de fissures',
  'מצב הקירות': 'État des murs',
  'איזה הכנה צריך?': 'Quelle préparation est nécessaire ?',
  'מה צריך? 🪵 (ניתן לבחור יותר מאחת)': 'De quoi avez-vous besoin ? 🪵 (plusieurs choix possibles)',
  'כמה פריטים?': 'Combien d\'objets ?',
  'מותג הריהוט (אם רלוונטי)': 'Marque du meuble (si pertinent)',
  'יש כלים בבית (מקדחה, פטיש...)': 'Il y a des outils à la maison (perceuse, marteau...)',
  'יש הוראות הרכבה / שרטוט': 'Il y a une notice de montage / plan',
  'מה צריך? ❄️': 'De quoi avez-vous besoin ? ❄️',
  'כמה יחידות?': 'Combien d\'unités ?',
  'סוג מזגן': 'Type de climatiseur',
  'גיל המזגן': 'Âge du climatiseur',
  'צריך הרכבה על הקיר (תליית יחידה פנימית)': 'Besoin de fixation murale (installation de l\'unité intérieure)',
  'גישה ליחידה החיצונית': 'Accès à l\'unité extérieure',
  'מה הבעיה? 🔐': 'Quel est le problème ? 🔐',
  '🚨 ננעלתי בחוץ כרגע — זה דחוף מאוד': '🚨 Je suis enfermé dehors en ce moment — c\'est très urgent',
  'סוג הדלת': 'Type de porte',
  'סוג המנעול (אם ידוע)': 'Type de serrure (si connu)',
  'מה קונים? 🛒 (ניתן לבחור יותר מאחד)': 'מה קונים? 🛒 (ניתן לבחור יותר מאחד)',
  'שם החנות / מיקום': 'Nom du magasin / localisation',
  'תקציב הקנייה (₪) משוער': 'Budget estimé des courses (₪)',
  'רשימת קניות': 'Liste de courses',
  'צריך להביא קבלה': 'Besoin de rapporter le reçu',
  'איך נשלם על הקנייה?': 'Comment régler les courses ?',
  'כתובת מסירה — לאן? *': 'Adresse de livraison — Où ?',
  'מה מוסרים?': 'Que faut-il livrer ?',
  'מתי צריך להגיע?': 'Quand faut-il passer ?',
  'שם המקבל (לא חובה)': 'Nom du destinataire (facultatif)',
  'טלפון המקבל (לא חובה)': 'Téléphone du destinataire (facultatif)',
  'שביר — יש לטפל בזהירות': 'Fragile — à manipuler avec précaution',
  'צריך שמירה על קור (קירור)': 'Nécessite une chaîne du froid (réfrigération)',
  'כמה ילדים?': 'Combien d\'enfants ?',
  'גילאי הילדים': 'Âge des enfants',
  'מתי נדרשת הבייביסיטר? 📅 (תאריך ושעות מדויקים)': 'Quand avez-vous besoin du baby-sitter ? 📅 (date et heures précises)',
  'איפה?': 'Où ?',
  'מה נדרש לעשות? (ניתן לבחור כמה)': 'Que faut-il faire ? (plusieurs choix possibles)',
  'צרכים מיוחדים / אלרגיות / מידע חשוב': 'Besoins spéciaux / allergies / informations importantes',
  'יש חיות מחמד בבית': 'Il y a des animaux de compagnie à la maison',
  'פרטי חיות המחמד': 'Détails sur les animaux',
  'נדרש ניסיון בעזרה ראשונה / החייאה': 'Expérience en secourisme / réanimation requise',
  'מעשנים בבית': 'Fumeurs à la maison',
  'איזה מקצוע? 📚': 'Quelle matière ? 📚',
  'כיתה / רמה': 'Classe / niveau',
  'מתי נדרש השיעור? 📅 (תאריך ושעות מדויקים)': 'Quand le cours est-il nécessaire ? 📅 (date et heures précises)',
  'פרונטלי או אונליין?': 'En présentiel ou en ligne ?',
  'מטרה / תיאור (לא חובה)': 'Objectif / description (facultatif)',
  'יש לקות למידה / ADHD (נדרשת התאמה)': 'Trouble de l\'apprentissage / TDAH (adaptation requise)',
  'מה הבעיה? 💻 (ניתן לבחור יותר מאחת)': 'Quel est le problème ? 💻 (plusieurs choix possibles)',
  'איזה מכשיר?': 'Quel appareil ?',
  'מערכת הפעלה (אם ידוע)': 'Système d\'exploitation (si connu)',
  'איך מועדף?': 'Quel mode préférez-vous ?',
  '⚠️ יש נתונים חשובים שעלולים לאבד': '⚠️ Il y a des données importantes qui risquent d\'être perdues',
  'מה צריך לעשות? 🔨 (ניתן לבחור יותר מאחת)': 'Que faut-il faire ? 🔨 (plusieurs choix possibles)',
  'סוג הקיר (אם רלוונטי)': 'Type de mur (si pertinent)',
  'כמה עבודות / פריטים?': 'Combien de travaux / objets ?',
  'מה צריך? 💪': 'De quoi avez-vous besoin ? 💪',
  'מה מזיזים?': 'Que faut-il déplacer ?',
  'משקל משוער לפריט': 'Poids estimé par objet',
  'קומה (אם רלוונטי)': 'Étage (si pertinent)',
  'כמה עוזרים צריך?': 'Combien d\'aides sont nécessaires ?',
  'מה צריך? 🏠 (ניתן לבחור יותר מאחת)': 'De quoi avez-vous besoin ? 🏠 (plusieurs choix possibles)',
  'גודל השטח / היקף העבודה': 'Taille de la zone / étendue des travaux',
  'צריך לפנות / להשליך ציוד': 'Besoin d\'évacuer / jeter du matériel',
  'מה מפנים?': 'Que faut-il évacuer ?',
  'איזה סוג נסיעה? 🚗': 'Quel type de trajet ? 🚗',
  'לאן נוסעים? *': 'Où allez-vous ? *',
  'כמה נוסעים?': 'Combien de passagers ?',
  'יש כבודה גדולה / מזוודות': 'Il y a des bagages volumineux',
  'כמה מזוודות?': 'Combien de valises ?',
  'צריך כיסא בטיחות לילד': 'Besoin d\'un siège auto enfant',
  'כמה כיסאות בטיחות?': 'Combien de sièges auto ?',
  'מה צריך? 🐶': 'De quoi avez-vous besoin ? 🐶',
  'איזה חיה?': 'Quel animal ?',
  'גודל הכלב': 'Taille du chien',
  'גזע הכלב (אם ידוע)': 'Race du chien (si connue)',
  'גיל הכלב': 'Âge du chien',
  'אופי הכלב — ניתן לבחור כמה': 'Caractère du chien — plusieurs choix possibles',
  'הכלב מסתדר עם כלבים אחרים?': 'Le chien s\'entend-il avec d\'autres chiens ?',
  'מחוסן ומעודכן': 'Vacciné et à jour',
  'מסורס / מעוקר': 'Castré / stérilisé',
  'בית עם ילדים': 'Maison avec enfants',
  'בית עם חתולים': 'Maison avec chats',
  'חתול ביתי (לא יוצא החוצה)': 'Chat d\'intérieur (ne sort pas)',
  'צריך החלפת חול / ניקוי ארגז': 'Besoin de changer la litière / nettoyer le bac',
  'מתי נדרש השירות? 📅 (תאריך ושעות מדויקים)': 'Quand le service est-il nécessaire ? 📅 (date et heures précises)',
  'הוראות האכלה / תרופות': 'Instructions d\'alimentation / médicaments',
  'צרכים מיוחדים / מצב רפואי': 'Besoins spéciaux / condition médicale',
  'העובד יקבל מפתח לבית': 'L\'intervenant aura un jeu de clés',
  'מה צריך? 👵 (ניתן לבחור יותר מאחת)': 'De quoi avez-vous besoin ? 👵 (plusieurs choix possibles)',
  'מתי נדרש הסיוע? 📅 (תאריך ושעות מדויקים)': 'Quand l\'aide est-elle nécessaire ? 📅 (date et heures précises)',
  'מצב הניידות של הקשיש': 'État de mobilité de la personne âgée',
  'הקשיש צריך הסעה (יש רכב משלו או שצריך רכב של העובד)': 'La personne âgée a besoin d\'un transport (a son propre véhicule ou besoin de celui de l\'intervenant)',
  'לקשיש יש רכב משלו': 'La personne âgée possède son propre véhicule',
  'מצב קוגניטיבי (אם רלוונטי)': 'État cognitif (si pertinent)',
  'נדרש תזכורת / עזרה בנטילת תרופות': 'Besoin d\'un rappel / aide pour la prise de médicaments',
  'שפה מועדפת (אם רלוונטי)': 'Langue préférée (si pertinent)',
  'איזה אימון? 🏋️ (ניתן לבחור יותר מאחד)': 'איזה אימון? 🏋️ (ניתן לבחור יותר מאחד)',
  'רמת הכושר שלך': 'Votre niveau de fitness',
  'מתי נדרש האימון? 📅 (תאריך ושעות מדויקים)': 'Quand l\'entraînement est-il nécessaire ? 📅 (date et heures précises)',
  'מטרה (לא חובה)': 'Objectif (facultatif)',
  'מגבלות רפואיות / פציעות (לא חובה)': 'Limitations médicales / blessures (facultatif)',
  'יש ציוד בבית (משקולות, מזרון...)': 'Il y a du matériel à la maison (poids, tapis...)',
  'מה צריך? 📸 (ניתן לבחור יותר מאחד)': 'מה צריך? 📸 (ניתן לבחור יותר מאחד)',
  'כמה זמן?': 'Combien de temps ?',
  'צריך עריכה + תמונות/סרטונים מוגמרים': 'Besoin de montage + photos/vidéos finales',
  'איזה עריכה?': 'Quel montage ?',
  'צריך צילום רחפן': 'Besoin de prise de vue par drone',
  'כמה תמונות / סרטונים סופיים צריך?': 'Combien de photos / vidéos finales ?',
  'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)': 'איזה תפקיד נדרש? 🎉 (ניתן לבחור יותר מאחד)',
  'סוג האירוע': 'Type d\'événement',
  'כמה אורחים?': 'Combien d\'invités ?',
  'כמה שעות?': 'Combien d\'heures ?',
  'נדרש מדים / תלבושת אחידה': 'Uniforme requis',
  'מה צריך? 🤝 (ניתן לבחור יותר מאחד)': 'מה צריך? 🤝 (ניתן לבחור יותר מאחד)',
  'מתי נדרשת העזרה? 📅 (תאריך ושעות מדויקים)': 'Quand l\'aide est-elle nécessaire ? 📅 (date et heures précises)',
  'צריך רכב משל העובד': 'Besoin du véhicule de l\'intervenant',
  'מערב ילדים (איסוף / הסעה)': 'Implique des enfants (récupération / transport)',
  'מה צריך? 🚗 (ניתן לבחור יותר מאחת)': 'De quoi avez-vous besoin ? 🚗 (plusieurs choix possibles)',
  'איזו תקלה? (אם יש)': 'Quelle panne ? (si présente)',
  'יצרן הרכב': 'Marque du véhicule',
  'שנתון הרכב': 'Année du véhicule',
  'איפה הרכב כעת?': 'Où se trouve le véhicule actuellement ?',
  '🚨 צריך גרירה / הובלת הרכב': '🚨 Besoin d\'un remorquage / transport du véhicule',
  'יש חלקי חילוף (לא צריך להביא)': 'J\'ai les pièces de rechange (pas besoin d\'en apporter)',
  'הערות נוספות (לא חובה)': 'Remarques supplémentaires (facultatif)',
  'נזילה ממקור מסוים': 'Fuite d\'une source spécifique',
  'סתימה בכיור / אמבטיה / שירותים': 'Évier / baignoire / toilettes bouchés',
  'החלפת ברז': 'Remplacement de robinet',
  'אסלה שלא מפסיקה לזרום': 'Chasse d\'eau qui fuit en continu',
  'דוד שמש / בוילר': 'Chauffe-eau solaire / électrique',
  'התקנת מכשיר חדש (מדיח, מכונת כביסה)': 'Installation d\'un nouvel appareil (lave-vaisselle, lave-linge)',
  'ריח / ביוב עולה': 'Odeur / remontées d\'égout',
  'בדיקה כללית': 'Vérification générale',
  'מטבח': 'Cuisine',
  'חדר אמבטיה': 'Salle de bain',
  'שירותים': 'Toilettes',
  'מרפסת': 'Balcon',
  'מחוץ לבית': 'Extérieur',
  'שקע / מפסק לא עובד': 'Prise / interrupteur ne fonctionne pas',
  'נפילת חשמל (מפסק קפץ)': 'Coupure de courant (disjoncteur sauté)',
  'התקנת שקע חדש': 'Installation d\'une nouvelle prise',
  'החלפת נורה / גוף תאורה': 'Changement d\'ampoule / luminaire',
  'בדיקת לוח חשמל': 'Vérification du tableau électrique',
  'חיווט לחדר / מקום חדש': 'Câblage pour une nouvelle pièce / emplacement',
  'התקנת מאוורר תקרה': 'Installation d\'un ventilateur de plafond',
  'חיווט לדוד / למזגן': 'Câblage pour chauffe-eau / climatiseur',
  'סלון': 'Salon',
  'חדר שינה': 'Chambre',
  'כל הבית': 'Toute la maison',
  'כיסוח דשא': 'Tonte de pelouse',
  'גיזום עצים / שיחים': 'Taille d\'arbres / arbustes',
  'עישוב (ניכוש עשבים)': 'Désherbage',
  'ניקוי וסידור הגינה': 'Nettoyage et rangement du jardin',
  'פינוי ענפים / גזם': 'Évacuation des branches / déchets verts',
  'שתילה / הקמת ערוגה': 'Plantation / création d\'un parterre',
  'תכנון והקמת גינה חדשה': 'Conception et création d\'un nouveau jardin',
  'תיקון מערכת השקיה': 'Réparation du système d\'arrosage',
  'קטנה — עד 20 מ"ר': 'Petite — jusqu\'à 20 m²',
  'בינונית — 20–60 מ"ר': 'Moyenne — 20–60 m²',
  'גדולה — 60–150 מ"ר': 'Grande — 60–150 m²',
  'גדולה מאוד — מעל 150 מ"ר': 'Très grande — plus de 150 m²',
  'גינה פרטית בבית': 'Jardin privé',
  'גינת בניין משותף': 'Jardin de copropriété',
  'מרפסת / גג': 'Balcon / toit-terrasse',
  'שטח ציבורי / עסקי': 'Espace public / commercial',
  'חד-פעמי': 'Unique',
  'שבועי': 'Hebdomadaire',
  'דו-שבועי': 'Bimensuel',
  'חודשי': 'Mensuel',
  'ניקיון שוטף (שבועי / דו-שבועי)': 'Nettoyage courant (hebdomadaire / bimensuel)',
  'ניקוי עומק (אחת לחודש)': 'Nettoyage en profondeur (mensuel)',
  'ניקיון לפני / אחרי מעבר דירה': 'Nettoyage avant / après déménagement',
  'ניקיון לאחר שיפוץ': 'Nettoyage après travaux',
  'ניקוי חלונות': 'Nettoyage des vitres',
  'ניקוי שטיחים / ריפוד': 'Nettoyage de tapis / canapés',
  'ניקוי מטבח / תנור': 'Nettoyage cuisine / four',
  'ניקוי משרד / עסק': 'Nettoyage bureau / entreprise',
  'דירה': 'Appartement',
  'בית פרטי': 'Maison individuelle',
  'משרד': 'Bureau',
  'מחסן / חדר': 'Débarras / pièce',
  'מעבר דירה מלא': 'Déménagement complet',
  'כמה פריטים / ארגזים': 'Nombre d\'objets / cartons',
  'רהיט בודד (ספה, מיטה, ארון)': 'Meuble seul (canapé, lit, armoire)',
  'ציוד / מכשיר גדול': 'Matériel / appareil volumineux',
  'טנדר / סטיישן מספיק': 'Fourgonnette / break suffisant',
  'ואן בינוני': 'Fourgon moyen',
  'משאית קטנה': 'Petit camion',
  'משאית גדולה': 'Gros camion',
  'לא בטוח': 'Pas sûr',
  'קירות פנים (חדר / דירה)': 'Murs intérieurs (pièce / appartement)',
  'תקרה': 'Plafond',
  'קירות חוץ': 'Murs extérieurs',
  'גדר / קיר חיצוני': 'Clôture / mur extérieur',
  'דלת / חלון': 'Porte / fenêtre',
  'ריהוט עץ': 'Meubles en bois',
  'מדרגות': 'Escaliers',
  'חדש — רק צבע': 'Neuf — juste peinture',
  'תקין — צריך שכבה': 'En bon état — juste une couche',
  'דורש תיקון קל': 'Nécessite une réparation légère',
  'דורש שיפוץ מקדים': 'Nécessite une remise en état préalable',
  'טיח / מריחת גבס': 'Enduit / plâtre',
  'סתימת סדקים': 'Rebouchage de fissures',
  'הסרת טפט ישן': 'Décollage de vieux papier peint',
  'שיוף קיר ישן': 'Ponçage de vieux mur',
  'תיקון רטיבות': 'Réparation humidité',
  'תיקון / חיזוק רהיט שבור': 'Réparation / renfort de meuble cassé',
  'בניית מדף / ארון מותאם': 'Construction d\'étagère / placard sur mesure',
  'החלפת / תיקון דלת': 'Remplacement / réparation de porte',
  'התקנת מטבח / ארונות': 'Installation de cuisine / placards',
  'עבודת עץ מותאמת אישית': 'Menuiserie sur mesure',
  'פירוק רהיטים': 'Démontage de meubles',
  'פריט אחד': 'Un seul objet',
  '2–3 פריטים': '2–3 objets',
  '4–6 פריטים': '4–6 objets',
  'יותר מ-6': 'Plus de 6',
  'הום סנטר': 'Home Center',
  'אייס': 'ACE',
  'לא רלוונטי': 'Non pertinent',
  'התקנת מזגן חדש': 'Installation nouveau climatiseur',
  'פירוק מזגן': 'Démontage climatiseur',
  'ניקוי / שירות שנתי': 'Nettoyage / entretien annuel',
  'מזגן לא מקרר / לא מחמם': 'Le climatiseur ne refroidit/chauffe pas',
  'מזגן מטפטף מים': 'Le climatiseur fuit de l\'eau',
  'מזגן לא נדלק': 'Le climatiseur ne s\'allume pas',
  'רעש / רטיט במזגן': 'Bruit / vibration dans le climatiseur',
  'מפוצל (split)': 'Split',
  'נייד': 'Mobile',
  'מיני מרכזי': 'Mini centralisé',
  'מרכזי / תעלות': 'Centralisé / par conduits',
  'לא יודע': 'Je ne sais pas',
  'חדש (עד שנתיים)': 'Neuf (jusqu\'à 2 ans)',
  'מעל 7 שנים': 'Plus de 7 ans',
  'מרפסת / גג נגיש': 'Balcon / toit accessible',
  'צריך סולם': 'Besoin d\'une échelle',
  'צריך בניין / סנפלינג': 'Accès difficile / travail en hauteur',
  '🚨 ננעלתי בחוץ — פריצת מנעול': '🚨 Je suis enfermé dehors — ouverture de porte',
  'החלפת מנעול': 'Changement de serrure',
  'התקנת מנעול חדש / חיזוק': 'Installation nouvelle serrure / renforcement',
  'שכפול מפתח': 'Duplication de clé',
  'תיקון / ידית דלת': 'Réparation / poignée de porte',
  'כספת — פתיחה / התקנה': 'Coffre-fort — ouverture / installation',
  'צילינדר חסום / מפתח שבור בפנים': 'Cylindre bloqué / clé cassée à l\'intérieur',
  'דלת דירה': 'Porte d\'appartement',
  'דלת בית פרטי': 'Porte de maison',
  'דלת מחסן / חניה': 'Porte de débarras / garage',
  'דלת משרד': 'Porte de bureau',
  'מכונית': 'Voiture',
  'צילינדר רגיל': 'Cylindre standard',
  'מולטילוק': 'Mul-T-Lock',
  'מנעול חכם / קוד': 'Serrure connectée / code',
  'בריח': 'Verrou',
  'מזון (סופר / מכולת)': 'Alimentation (supermarché / épicerie)',
  'תרופות / בית מרקחת': 'Médicaments / pharmacie',
  'פירות וירקות (שוק)': 'Fruits et légumes (marché)',
  'ציוד / חנות ספציפית': 'Matériel / magasin spécifique',
  'אלכוהול': 'Alcool',
  'קניות כלליות — יסופק רשימה': 'Courses générales — liste fournie',
  'מזומן בחזרה': 'Cashback',
  'העברה בביט': 'Virement Bit',
  'אשראי': 'Carte de crédit',
  'מסמכים / מעטפה': 'Documents / enveloppe',
  'חבילה קטנה (כמו נעליים)': 'Petit colis (ex: chaussures)',
  'חבילה בינונית (כמו מזוודה)': 'Colis moyen (ex: valise)',
  'חבילה גדולה / כבדה': 'Colis volumineux / lourd',
  'אוכל / מזון': 'Aliments / repas',
  'תרופות': 'Médicaments',
  '🔴 מיידי — תוך שעה': '🔴 Immédiat — dans l\'heure',
  'היום עד שעה מסוימת': 'Aujourd\'hui avant une heure précise',
  'היום — גמיש': 'Aujourd\'hui — flexible',
  'מחר': 'Demain',
  'גמיש לחלוטין': 'Complètement flexible',
  'בבית שלנו': 'À notre domicile',
  'בבית הבייביסיטר': 'Au domicile du baby-sitter',
  'גמיש': 'Flexible',
  'שמירה בלבד': 'Garde uniquement',
  'הכנת ארוחה': 'Préparation de repas',
  'השכבה לשינה': 'Coucher',
  'עזרה בשיעורים': 'Aide aux devoirs',
  'אמבטיה': 'Bain',
  'הסעה / איסוף מגן': 'Transport / ramassage scolaire',
  'משחק ופעילות': 'Jeux et activités',
  'כיתה א-ו (יסודי)': 'Primaire (CP-CM2)',
  'כיתה ז-ט (חטיבה)': 'Collège (6ème-3ème)',
  'כיתה י-יב (תיכון)': 'Lycée (2nde-Terminale)',
  'הכנה לבגרות': 'Préparation au Bac',
  'אקדמיה / אוניברסיטה': 'Enseignement supérieur / Université',
  'מבוגר': 'Adulte',
  'פרונטלי — בבית': 'En présentiel — à la maison',
  'פרונטלי — אצל המורה': 'En présentiel — chez l\'enseignant',
  'זום / אונליין': 'Zoom / En ligne',
  'מחשב איטי מאוד': 'Ordinateur très lent',
  'מחשב לא נדלק': 'L\'ordinateur ne s\'allume pas',
  'וירוס / תוכנה זדונית': 'Virus / logiciel malveillant',
  'בעיית אינטרנט / WiFi': 'Problème Internet / WiFi',
  'התקנת תוכנה / Windows': 'Installation logiciel / Windows',
  'גיבוי נתונים / שחזור': 'Sauvegarde / restauration de données',
  'בעיית מסך / מקלדת / עכבר': 'Problème écran / clavier / souris',
  'הגדרת אימייל / חשבון': 'Configuration e-mail / compte',
  'התקנת מדפסת': 'Installation imprimante',
  'מחשב נייח': 'PC fixe',
  'לפטופ (נייד)': 'Ordinateur portable',
  'טאבלט': 'Tablette',
  'סמארטפון': 'Smartphone',
  'ראוטר / רשת': 'Routeur / réseau',
  'מדפסת': 'Imprimante',
  'כמה מכשירים': 'Combien d\'appareils',
  'ביקור בית / עסק': 'Visite à domicile / bureau',
  'מרחוק (remote)': 'À distance (télémaintenance)',
  'תליית טלוויזיה על קיר': 'Fixation TV murale',
  'תליית מדף / תמונה': 'Fixation étagère / cadre',
  'התקנת וילון / בלינד': 'Installation rideau / store',
  'החלפת ידית / מנגנון': 'Remplacement poignée / mécanisme',
  'תיקון ריהוט שבור': 'Réparation de meubles cassés',
  'הרכבת ריהוט מקופסה': 'Montage de meubles en kit',
  'איטום / גבס קטן': 'Étanchéité / petits travaux plâtre',
  'התקנת מנורה / גוף תאורה': 'Installation lampe / luminaire',
  'תיקון דלת / ציר': 'Réparation porte / charnière',
  'בטון / בלוק': 'Béton / parpaing',
  'גבס': 'Plâtre / placo',
  'עבודה אחת': 'Une seule intervention',
  '2–3 עבודות': '2–3 interventions',
  '4 ומעלה': '4 et plus',
  'להעלות / להוריד פריט כבד': 'Monter / descendre un objet lourd',
  'לסחוב ארגזים / קרטונים': 'Transporter des cartons',
  'פריקת משאית / ואן': 'Déchargement camion / fourgon',
  'עזרה בהזזת ריהוט בתוך הבית': 'Aide pour déplacer des meubles dans la maison',
  'עזרה במעבר דירה (ללא נהג)': 'Aide au déménagement (sans chauffeur)',
  'טעינת פריטים לרכב': 'Chargement d\'objets dans le véhicule',
  'עד 15 ק"ג': 'Jusqu\'à 15 kg',
  '15–30 ק"ג': '15–30 kg',
  '30–60 ק"ג': '30–60 kg',
  'מעל 60 ק"ג': 'Plus de 60 kg',
  'ארגזים רבים': 'Nombreux cartons',
  'קרקע': 'Rez-de-chaussée',
  'קומה 1': '1er étage',
  'קומה 2': '2ème étage',
  'קומה 3+': '3ème étage et plus',
  'יש מעלית': 'Il y a un ascenseur',
  'אחד מספיק': 'Un suffit',
  'שניים': 'Deux',
  'שלושה ומעלה': 'Trois et plus',
  'ניקוי / פינוי מחסן': 'Nettoyage / évacuation débarras',
  'סידור וארגון מחסן': 'Rangement et organisation débarras',
  'ניקוי מרזבים / גג': 'Nettoyage gouttières / toit',
  'פינוי פסולת / ריהוט ישן': 'Évacuation déchets / vieux meubles',
  'ניקוי מרפסת / חצר': 'Nettoyage balcon / cour',
  'ארגון בית כללי': 'Organisation générale de la maison',
  'תיקונים קטנים בבית': 'Petits travaux de maison',
  'קטן — עד שעה': 'Petit — jusqu\'à 1 heure',
  'בינוני — 2–3 שעות': 'Moyen — 2–3 heures',
  'גדול — חצי יום': 'Grand — demi-journée',
  'גדול מאוד — יום שלם': 'Très grand — journée complète',
  'ריהוט ישן': 'Vieux meubles',
  'פסולת בניין': 'Déchets de chantier',
  'קרטונים': 'Cartons',
  'גזם / ענפים': 'Déchets verts / branches',
  'ציוד חשמלי': 'Équipement électrique',
  'אשפה כללית': 'Déchets ménagers',
  'נסיעה לשדה התעופה / ממנו': 'Trajet vers / depuis l\'aéroport',
  'הסעה לאירוע': 'Transport événement',
  'הסעת ילדים (גן / בית ספר / חוגים)': 'Transport enfants (école / activités)',
  'טרמפ לעבודה / עיר אחרת': 'Covoiturage travail / ville voisine',
  'נהג פרטי לכמה שעות': 'Chauffeur privé pour quelques heures',
  'נסיעה לבית חולים / קופת חולים': 'Transport hôpital / centre médical',
  'הסעת קשיש': 'Transport personne âgée',
  '1': '1',
  '1–2': '1–2',
  'טיול עם הכלב': 'Promenade du chien',
  'שמירה / פנסיון בבית המטפל': 'Garde / pension au domicile de l\'intervenant',
  'ביקור יומי (האכלה / השקיה / טיול קצר)': 'Visite quotidienne (nourrissage / arrosage / balade)',
  'הסעה לוטרינר / טיפוח': 'Transport vétérinaire / toilettage',
  'אילוף / אימון': 'Dressage / éducation',
  'טיפוח / גזיזה / אמבטיה': 'Toilettage / tonte / bain',
  'כלב': 'Chien',
  'חתול': 'Chat',
  'ארנב / מכרסם': 'Lapin / rongeur',
  'ציפור': 'Oiseau',
  'זוחל': 'Reptile',
  'דגים': 'Poissons',
  'כמה חיות': 'Nombre d\'animaux',
  'קטן — עד 10 ק"ג': 'Petit — jusqu\'à 10 kg',
  'בינוני — 10–25 ק"ג': 'Moyen — 10–25 kg',
  'גדול — 25–45 ק"ג': 'Grand — 25–45 kg',
  'ענק — מעל 45 ק"ג': 'Géant — plus de 45 kg',
  'גור (עד שנה)': 'Chiot / jeune (jusqu\'à 1 an)',
  'צעיר (1–3 שנים)': 'Jeune (1–3 ans)',
  'בוגר (3–7 שנים)': 'Adulte (3–7 ans)',
  'מבוגר (מעל 7)': 'Sénior (plus de 7)',
  'ידידותי': 'Amical',
  'רגוע': 'Calme',
  'אנרגטי': 'Énergique',
  'חרדתי': 'Anxieux',
  'תקיף / תוקפני': 'Agressif',
  'מושך ברצועה': 'Tire en laisse',
  'בורח לפעמים': 'S\'échappe parfois',
  'כן, ידידותי': 'Oui, amical',
  'בסדר עם היכרות': 'OK après rencontre',
  'מסתייג': 'Méfiant',
  'ליווי לרופא / קופת חולים': 'Accompagnement médecin / centre médical',
  'ליווי לבית מרקחת / קניות': 'Accompagnement pharmacie / courses',
  'קניות עבור הקשיש': 'Courses pour la personne âgée',
  'עזרה בבית (כביסה, ניקיון קל)': 'Aide à la maison (lessive, ménage léger)',
  'חברה וביקור (שיחה, הליכה)': 'Compagnie et visite (discussion, balade)',
  'עזרה בטכנולוגיה (טלפון, מחשב)': 'Aide technologique (téléphone, ordinateur)',
  'עזרה בטפסים / ביורוקרטיה': 'Aide aux formulaires / bureaucratie',
  'הכנת ארוחה': 'Préparation de repas',
  'הולך באופן עצמאי': 'Marche de manière autonome',
  'זקוק לעזרה בהליכה / תמיכה': 'Besoin d\'aide pour marcher / soutien',
  'מרותק לכיסא גלגלים': 'En fauteuil roulant',
  'מרותק למיטה': 'Alité',
  'צלול ועצמאי': 'Lucide et autonome',
  'זיכרון ירוד קל': 'Légers troubles de la mémoire',
  'דמנציה / אלצהיימר': 'Démence / Alzheimer',
  'אימון כושר כללי': 'Fitness général',
  'ריצה / הכנה לריצה': 'Course à pied / préparation running',
  'יוגה': 'Yoga',
  'פילאטיס': 'Pilates',
  'אימון כוח / הרמת משקולות': 'Renforcement musculaire / musculation',
  'אימון בית (ללא ציוד)': 'Entraînement à domicile (sans matériel)',
  'אימון בחדר כושר': 'Entraînement en salle de sport',
  'שחייה': 'Natation',
  'אימון תפקודי / שיקום': 'Entraînement fonctionnel / rééducation',
  'מתחיל לגמרי': 'Débutant complet',
  'בסיסי': 'Basique',
  'בינוני': 'Moyen',
  'מתקדם': 'Avancé',
  'בבית': 'À domicile',
  'בפארק / בחוץ': 'Au parc / en extérieur',
  'בחדר כושר': 'En salle de sport',
  'צילום עסק / חנות': 'Shooting entreprise / magasin',
  'צילום מוצרים': 'Shooting produits',
  'צילום אירוע (מסיבה / אירוע עסקי)': 'Shooting événement (fête / événement pro)',
  'צילום אישי / תדמית': 'Shooting portrait / image de marque',
  'סרטון לרשתות (רילס / טיקטוק)': 'Vidéo réseaux sociaux (Reels / TikTok)',
  'עריכת וידאו בלבד': 'Montage vidéo uniquement',
  'עריכת תמונות בלבד': 'Retouche photo uniquement',
  'צילום נדל"ן / דירה': 'Photo immobilier / appartement',
  'עד שעה': 'Jusqu\'à 1 heure',
  'שעה-שעתיים': '1 à 2 heures',
  'חצי יום': 'Demi-journée',
  'יום מלא': 'Journée complète',
  'צבע והתאמה': 'Couleur et ajustement',
  'הסרת רקע': 'Suppression d\'arrière-plan',
  'טקסט / כותרות': 'Texte / titres',
  'מוזיקה': 'Musique',
  'כתוביות': 'Sous-titres',
  'קיצור ומעברים': 'Coupe et transitions',
  'מלצר / הגשה': 'Serveur / service',
  'ברמן': 'Barman',
  'שף / טבח': 'Chef / cuisinier',
  'הפעלת ילדים / אנימציה': 'Animation enfants',
  'עזרה בהקמה / פירוק': 'Aide montage / démontage',
  'סדרן / אבטחה': 'Placeur / sécurité',
  'DJ / מוזיקה': 'DJ / musique',
  'צלם (ראה קטגוריה צילום)': 'Photographe (voir catégorie photo)',
  'מסיבה פרטית': 'Fête privée',
  'אירוע עסקי': 'Événement professionnel',
  'חתונה / בר מצווה': 'Mariage / Bar-Mitzvah',
  'אירוע ילדים': 'Événement enfants',
  'יום הולדת': 'Anniversaire',
  'עד 20': 'Jusqu\'à 20',
  '20–50': '20–50',
  '50–100': '50–100',
  '100–200': '100–200',
  'מעל 200': 'Plus de 200',
  'עד 3 שעות': 'Jusqu\'à 3 heures',
  '5–8 שעות': '5–8 heures',
  'לחכות לטכנאי / שליח בבית': 'Attendre un technicien / livreur',
  'לעמוד בתור (עיריה, רופא, דואר)': 'Faire la queue (mairie, médecin, poste)',
  'לאסוף / להחזיר ילד מגן / בית ספר': 'Récupérer / ramener un enfant de l\'école',
  'להעביר מפתח / מסמך': 'Transmettre une clé / document',
  'להחזיר ציוד / פריט לחנות': 'Rendre du matériel / article au magasin',
  'לבדוק / לצלם דירה': 'Vérifier / photographier un appartement',
  'עזרה בטפסים / ביורוקרטיה': 'Aide aux formulaires / bureaucratie',
  'שליחות אישית': 'Course personnelle',
  'טיפול ותחזוקה שוטפת': 'Traitement et entretien régulier',
  'תיקון תקלה / אבחון': 'Réparation panne / diagnostic',
  'החלפת מצבר': 'Changement de batterie',
  'החלפת בלמים / רפידות': 'Changement freins / plaquettes',
  'החלפת שמן + פילטרים': 'Vidange + filtres',
  'החלפת צמיגים / גלגלים': 'Changement pneus / roues',
  'בדיקת מחשב (דיאגנוסטיקה)': 'Contrôle informatique (diagnostic)',
  'טיפול מוסך מלא': 'Entretien complet garage',
  'הזנקה (פנצר / כבלים)': 'Dépannage (crevaison / câbles)',
  'שטיפת רכב / ניקוי': 'Lavage véhicule / nettoyage',
  'מזגן רכב': 'Climatisation voiture',
  'הרכב לא מתניע': 'Le véhicule ne démarre pas',
  'רעשים מהמנוע': 'Bruits moteur',
  'אור אזהרה דולק בלוח': 'Voyant allumé au tableau de bord',
  'בלמים לא תקינים / רעש': 'Freins défectueux / bruit',
  'בעיית הילוכים': 'Problème boîte de vitesses',
  'דליפת נוזל / שמן': 'Fuite liquide / huile',
  'מזגן לא עובד': 'Climatisation en panne',
  'חשמל / אלקטרוניקה': 'Électricité / électronique',
  'אין תקלה — טיפול שוטף': 'Pas de panne — entretien courant',
  'טויוטה': 'Toyota',
  'מאזדה': 'Mazda',
  'הונדה': 'Honda',
  'יונדאי': 'Hyundai',
  'קיה': 'Kia',
  'סקודה': 'Skoda',
  'פולקסווגן': 'Volkswagen',
  'מרצדס': 'Mercedes',
  'אאודי': 'Audi',
  'רנו': 'Renault',
  'ניסאן': 'Nissan',
  'מיצובישי': 'Mitsubishi',
  'סובארו': 'Subaru',
  'וולבו': 'Volvo',
  'טסלה': 'Tesla',
  'פורד': 'Ford',
  'שברולט': 'Chevrolet',
  'בבית / ברחוב': 'À la maison / dans la rue',
  'במוסך': 'Au garage',
  'בצד הדרך (תקוע)': 'Sur le bord de la route (en panne)',
  'צריך גרירה למוסך': 'Besoin d\'un remorquage au garage',
  'הטכנאי מגיע אליי': 'Le technicien vient chez moi',
  'אני מגיע למוסך': 'J\'amène le véhicule au garage',
  'אחר': 'Autre',
  'Windows': 'Windows',
  'Mac / macOS': 'Mac / macOS',
  'Linux': 'Linux',
  'iOS / iPad': 'iOS / iPad',
  'Android': 'Android',
  'IKEA': 'IKEA',
  'KARE': 'KARE',
  'PayBox': 'PayBox',
  'BMW': 'BMW',
  'למשל: 3': 'Exemple: 3',
  'למשל: 2': 'Exemple: 2',
  'למשל: 50': 'Exemple: 50',
  'למשל: 2018': 'Exemple: 2018',
  'למשל: 20': 'Exemple: 20',
  '0 = קרקע': '0 = rez-de-chaussée',
  'עיר, רחוב...': 'Ville, rue...',
  'עיר, רחוב, מספר...': 'Ville, rue, numéro...',
  'כתובת יעד...': 'Adresse de destination...',
  'למשל: סופר רמי לוי, רחוב הרצל...': 'Exemple: Supermarché Rami Levy, rue Herzl...',
  'למשל: 200': 'Exemple: 200',
  'חלב, לחם, עגבניות, ביצים...': 'Lait, pain, tomates, œufs...',
  'למשל: דוד כהן': 'Exemple: David Cohen',
  'למשל: 050-1234567': 'Exemple: 050-1234567',
  'למשל: ספה גדולה, 3 ארגזים, מקרר...': 'Exemple: grand canapé, 3 cartons, réfrigérateur...',
  'למשל: מקרר אמריקאי, 10 ארגזים...': 'Exemple: réfrigérateur américain, 10 cartons...',
  'למשל: מתמטיקה, אנגלית, פיזיקה...': 'Exemple: mathématiques, anglais, physique...',
  'למשל: הכנה למבחן בגרות, צמצום פערים...': 'Exemple: préparation au Bac, rattrapage scolaire...',
  'למשל: 1.5 שנים, 4, 7': 'Exemple: 1,5 ans, 4, 7',
  'למשל: לברדור, פודל, מעורב...': 'Exemple: Labrador, Caniche, croisé...',
  'למשל: 2 פעמים ביום, תרופה בבוקר...': 'Exemple: 2 fois par jour, médicament le matin...',
  'למשל: סכרת, אפילפסיה, אלרגיות...': 'Exemple: diabète, épilepsie, allergies...',
  'למשל: אלרגיה לבוטנים, ילד עם אוטיזם, תרופות...': 'Exemple: allergie aux arachides, enfant autiste, médicaments...',
  'למשל: כלב ידידותי, חתול...': 'Exemple: chien amical, chat...',
  'למשל: רוסית, רומנית, ערבית...': 'Exemple: russe, roumain, arabe...',
  'למשל: לרדת 5 קילו, להתכונן לריצת 10K...': 'Exemple: perdre 5 kg, se préparer pour un 10 km...',
  'למשל: בעיות גב, ברך פגועה, לחץ דם...': 'Exemple: problèmes de dos, genou blessé, tension artérielle...',
  'למשל: הרכב מתניע אבל משמיע רעש מוזר, נראה שהמצבר...': 'Exemple: la voiture démarre mais fait un bruit bizarre, on dirait la batterie...',
  'למשל: עבודה אחת': 'Exemple: une seule intervention',
};
export default fr;
